Repository gladiaio/gladia, pull requests merged in 2022-10, with the labels that each got.

#835 fix(main): non activated route are now longer miss-activated
  src/main.py
Labels: priority: medium, status : confirmed, type: fix, ci: ready-to-merge

#829 feat(conversation-summarization): add conversation-summarization + fix summarization output
  src/apis/text/text/conversation-summarization-models/.task_metadata.yaml
  src/apis/text/text/conversation-summarization-models/__init__.py
  src/apis/text/text/conversation-summarization-models/bart-large-xsum-samsum/.model_metadata.yaml
  src/apis/text/text/conversation-summarization-models/bart-large-xsum-samsum/__init__.py
  src/apis/text/text/conversation-summarization-models/bart-large-xsum-samsum/bart-large-xsum-samsum.py
  src/apis/text/text/conversation-summarization-models/test_conversation-summarization.py
  src/apis/text/text/conversation-summarization.py
  src/apis/text/text/summarization-models/all-MiniLM-L6-v2/all-MiniLM-L6-v2.py
Labels: type: enhancement, help wanted, ci: ready-to-merge

#841 fix(TaskRouter): handle invalid url (#838)
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#840 fix(TaskRouter): raise HTTPException when clean_kwargs_based_on_router_inputs fails (#839)
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#842 test(autogenerator): test auto generator
  .github/workflows/gladia-builder.yml
  src/api_utils/gladia_api_utils/submodules.py
  src/api_utils/gladia_api_utils/task_management.py
  src/apis/image/image/background-removal-models/test_background_removal.py
  src/apis/image/image/colorization-models/test_colorization.py
  src/apis/image/image/deblurring-models/test_deblurring.py
  src/apis/image/image/enhancement-models/test_enhancement.py
  src/apis/image/image/face-bluring-models/test_face_blurring.py
  src/apis/image/image/super-resolution-models/test_super_resolution.py
  src/apis/image/image/uncolorization-models/test_uncolorization.py
  src/apis/text/text/autocorrect-models/test_autocorrect.py
  src/apis/text/text/conversation-summarization-models/test_conversation-summarization.py
  src/apis/text/text/emotion-recognition-models/test_emotion_recognition.py
  src/apis/text/text/hate-speech-detection-models/test_hate_speech_detection.py
  src/apis/text/text/headline-generation-models/test_headline_generation.py
  src/apis/text/text/keyword-extraction-models/test_keyword_extraction.py
  src/apis/text/text/language-detection-models/test_language_detection.py
  src/apis/text/text/language-generation-models/test_language_generation.py
  src/apis/text/text/named-entity-recognition-models/test_named_entity_recognition.py
  src/apis/text/text/next-sentence-prediction-models/test_next_sentence_prediction.py
  src/apis/text/text/next-word-prediction-models/test_next_word_prediction.py
  src/apis/text/text/programming-language-generation-models/test_programming_language_generation.py
  src/apis/text/text/question-answering-models/test_question_answering.py
  src/apis/text/text/sentence-paraphraser-models/test_sentence_paraphraser.py
  src/apis/text/text/sentiment-analysis-models/test_sentiment_analysis.py
  src/apis/text/text/similarity-models/test_similarity.py
  src/apis/text/text/summarization-models/test_summarization.py
  src/apis/text/text/translation-models/test_translation.py
  src/apis/text/text/word-alignment-models/test_word-aligment.py
  src/conftest.py
  src/pytest.ini
  src/tests/__init__.py
  src/tests/default_image_to_image_tests.py
  src/tests/default_tests.py
  src/tests/default_text_to_text_tests.py
  src/tests/test_autogenerated.py
Labels: priority: medium, status : confirmed, ci: force-build-gladia, type: test

#844 docs(test): basic README file
  src/tests/README.md
Labels: type: documentation, priority: low, status : confirmed, ci: ready-to-merge

#845 fix(submodule): error handling when the url is incorrect (#843)
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#847 refactor: delete deprecated UTs and metadata module
  src/api_utils/gladia_api_utils/metadata.py
  src/unit-test/config.json
  src/unit-test/test.jpg
  src/unit-test/test.m4a
  src/unit-test/test.mp3
  src/unit-test/test.png
  src/unit-test/test.py
  src/unit-test/test.wav
Labels: priority: low, type: refactor

#850 fix(textract-extractor): extract image content from empty pdf
  src/apis/image/text/ocr-models/textract-extractor/env.yaml
  src/apis/image/text/ocr-models/textract-extractor/textract-extractor.py
  src/base.Dockerfile
Labels: type: fix, ci: ready-to-merge, ci: build-base

#852 fix(guided-inpainting): fix guided-inpainting image resizing
  src/apis/image/image/guided-inpainting-models/stable-diffusion/stable-diffusion.py
Labels: type: fix, ci: ready-to-merge

#851 feat(geocoding): add geocoding
  src/apis/text/text/address_formating-models/.task_metadata.yaml
  src/apis/text/text/address_formating-models/__init__.py
  src/apis/text/text/address_formating-models/geopy-formatter/__init__.py
  src/apis/text/text/address_formating-models/geopy-formatter/geopy-formatter.py
  src/apis/text/text/address_formating.py
  src/env.yaml
Labels: type: enhancement, ci: ready-to-merge

#856 feat(gps-address): add gps address lookup
  src/apis/text/text/gps-address-formatting-models/.task_metadata.yaml
  src/apis/text/text/gps-address-formatting-models/__init__.py
  src/apis/text/text/gps-address-formatting-models/geopy-formatter/__init__.py
  src/apis/text/text/gps-address-formatting-models/geopy-formatter/geopy-formatter.py
  src/apis/text/text/gps-address-formatting.py
Labels: type: enhancement, ci: ready-to-merge

#855 fix(address-formatting): fix address-formatting naming convention
  src/apis/text/text/address-formatting-models/.task_metadata.yaml
  src/apis/text/text/address-formatting-models/__init__.py
  src/apis/text/text/address-formatting-models/geopy-formatter/__init__.py
  src/apis/text/text/address-formatting-models/geopy-formatter/geopy-formatter.py
  src/apis/text/text/address-formatting.py
Labels: type: fix, ci: ready-to-merge

#854 feat: triton client handles chkpts dir
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/api_utils/gladia_api_utils/triton_helper/download_active_models.py
  src/apis/text/image/image-generation-models/dream-studio/env.yaml
  src/apis/text/image/image-generation-models/stable-diffusion/stable-diffusion.py
  src/base.Dockerfile
  src/env.yaml
  src/gpu.Dockerfile
  src/warm_up.py
Labels: type: enhancement, priority: high, status : confirmed, ci: force-no-cache, ci: force-build-gladia, ci: build-base

#860 fix(background-removal): move from ANTIALIAS to LANCZOS
  src/apis/image/image/background-removal-models/OnnxBackgroundRemoval.py
  src/apis/image/image/background-replacement-models/.task_metadata.yaml
Labels: type: fix, ci: ready-to-merge

#859 build(base): fix fastertransformer triton backend
  src/base.Dockerfile
Labels: priority: high, ci: ready-to-merge, ci: build-base

#864 refactor(test): use requests instead of TestClient
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/image/image/background-replacement-models/test_background_replacement.py
  src/apis/image/image/guided-inpainting-models/test_guided_inpainting.py
  src/apis/image/image/inpainting-models/test_inpainting.py
  src/apis/image/text/asciify-models/test_asciify.py
  src/apis/image/text/classification-models/test_classification.py
  src/apis/image/text/ocr-models/test_ocr.py
  src/apis/text/image/image-generation-models/test_image_generation.py
  src/apis/text/text/headline-generation-models/test_headline_generation.py
  src/apis/text/text/keyword-extraction-models/test_keyword_extraction.py
  src/apis/text/text/next-sentence-prediction-models/test_next_sentence_prediction.py
  src/apis/text/text/next-word-prediction-models/test_next_word_prediction.py
  src/apis/text/text/question-answering-models/test_question_answering.py
  src/apis/text/text/similarity-models/test_similarity.py
  src/apis/text/text/summarization-models/test_summarization.py
  src/apis/text/text/translation-models/test_translation.py
  src/apis/text/text/word-alignment-models/test_word-aligment.py
  src/conftest.py
  src/tests/default_tests.py
  src/tests/test_autogenerated.py
Labels: priority: medium, status : confirmed, type: refactor, ci: ready-to-merge

#866 feat(deoldify): remove 500 error on deoldify model (#848)
  src/tools/venv-builder/envs/image/deoldify.yaml
Labels: type: dependencies, priority: high, status : confirmed, ci: ready-to-merge

#867 fix(stable-diffusion): fix unsafe return
  src/apis/text/image/image-generation-models/dream-studio/dream-studio.py
Labels: type: fix, ci: ready-to-merge

#868 fix(tests): change default port for tests server
  src/conftest.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#869 feat(tests): Support model name as a pattern (#853)
  src/tests/README.md
Labels: type: enhancement, priority: medium, status : confirmed, ci: ready-to-merge

#870 feat(punctuation-restoration): add punctuation restoration
  src/api_utils/gladia_api_utils/run_process.py
  src/apis/text/text/punctuation-restoration-models/.task_metadata.yaml
  src/apis/text/text/punctuation-restoration-models/__init__.py
  src/apis/text/text/punctuation-restoration-models/kredor-punctuate-all/.model_metadata.yaml
  src/apis/text/text/punctuation-restoration-models/kredor-punctuate-all/__init__.py
  src/apis/text/text/punctuation-restoration-models/kredor-punctuate-all/kredor-punctuate-all.py
  src/apis/text/text/punctuation-restoration.py
  src/env.yaml
Labels: type: enhancement, ci: ready-to-merge

#876 refactor(hate-speech-detection): remove Hate-speech-CNERG-dehatebert-mono-english
  src/apis/text/text/hate-speech-detection-models/Hate-speech-CNERG-dehatebert-mono-english/.git_path
  src/apis/text/text/hate-speech-detection-models/Hate-speech-CNERG-dehatebert-mono-english/.model_metadata.yaml
  src/apis/text/text/hate-speech-detection-models/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py
  src/apis/text/text/hate-speech-detection-models/Hate-speech-CNERG-dehatebert-mono-english/__init__.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge, ci: force-no-cache, ci: force-build-gladia, ci: build-base

#874 fix(submodule): fix enum collision name
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: fix, ci: ready-to-merge

#878 refactor(asciify-models): remove it
  src/apis/image/text/asciify-models/.task_metadata.yaml
  src/apis/image/text/asciify-models/__init__.py
  src/apis/image/text/asciify-models/ramesh-aditya/.model_metadata.yaml
  src/apis/image/text/asciify-models/ramesh-aditya/__init__.py
  src/apis/image/text/asciify-models/ramesh-aditya/ramesh-aditya.py
  src/apis/image/text/asciify-models/test_asciify.py
  src/apis/image/text/asciify.py
Labels: type: refactor, ci: ready-to-merge

#875 feat(anonymization): add text anonymization
  src/apis/text/text/anonymization-models/.task_metadata.yaml
  src/apis/text/text/anonymization-models/__init__.py
  src/apis/text/text/anonymization-models/ms-presidio/__init__.py
  src/apis/text/text/anonymization-models/ms-presidio/env.yaml
  src/apis/text/text/anonymization-models/ms-presidio/ms-presidio.py
  src/apis/text/text/anonymization.py
  src/env.yaml
  src/run_server.sh
Labels: type: enhancement, ci: ready-to-merge

#879 feat(whisper): add transcription segments
  src/apis/audio/text/audio-transcription-models/openai-whisper-base/openai-whisper-base.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-large/openai-whisper-large.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-medium/openai-whisper-medium.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-small/openai-whisper-small.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-tiny/openai-whisper-tiny.py
Labels: type: enhancement, ci: ready-to-merge
