Repository gladiaio/gladia, pull requests merged in 2022-08, with the labels that each got.

#513 fix(nlp-town): remove env.yaml to lower inference time
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/env.yaml
Labels: type: enhancement, priority: high, status : confirmed

#521 refactor(io): remove unused import magic
  src/api_utils/gladia_api_utils/io.py
Labels: type: enhancement, good first issue, priority: low, status : confirmed

#517 fix(nlp-town): move nlp town int representation to text
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
Labels: type: enhancement, priority: medium, status : confirmed

#516 fix(casting): fix int casting in formatted json output
  src/api_utils/gladia_api_utils/casting.py
Labels: type: enhancement, priority: high, status : confirmed

#523 Feat(keyword-extractions): add paraphrase minilm l6 v2 to Triton
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/api_utils/gladia_api_utils/triton_helper/data_processing.py
  src/api_utils/gladia_api_utils/triton_helper/download_active_models.py
  src/apis/text/text/keyword-extraction.py
  src/apis/text/text/keyword-extractions/keybert-paraphrase-MiniLM-L6-v2/.git_path
  src/apis/text/text/keyword-extractions/keybert-paraphrase-MiniLM-L6-v2/keybert-paraphrase-MiniLM-L6-v2.py
  src/config.json
Labels: type: new model, priority: low, status : confirmed

#530 refactor(config): remove unused value from root config file
  src/config.json
Labels: priority: low

#536 ci(linter): only PR-lint PR
  .github/labeler.yml
  .github/workflows/gladia-builder.yml
Labels: type: ci

#538 ci(builder): always build main
  .github/workflows/gladia-builder.yml
Labels: type: ci

#535 ci(test): remove second retry continue on error
  .github/workflows/gladia-builder.yml
Labels: type: ci

#528 fix(download_active_model): return only necessary paths
  src/api_utils/gladia_api_utils/triton_helper/download_active_models.py
Labels: type: bug, good first issue, priority: low, status : confirmed, type: fix

#539 ci(builder): let pytorch see all GPU
  .github/workflows/gladia-builder.yml
Labels: type: ci

#515 refactor(logger): replace print and icecream logs by logging logs
  .gitignore
  src/api_utils/gladia_api_utils/CoquiEngineHelper.py
  src/api_utils/gladia_api_utils/__init__.py
  src/api_utils/gladia_api_utils/file_management.py
  src/api_utils/gladia_api_utils/io.py
  src/api_utils/gladia_api_utils/model_management.py
  src/api_utils/gladia_api_utils/run_process.py
  src/api_utils/gladia_api_utils/submodules.py
  src/api_utils/gladia_api_utils/system.py
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/api_utils/setup.py
  src/env.yaml
  src/licenses-used.md
  src/main.py
  src/scaffold-model.py
  src/tools/venv-builder/create_custom_envs.py
Labels: priority: low, status : confirmed, type: refactor

#510 feat(test): input test files deduced from openapi
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/text/text/keyword-extraction.py
  src/unit-test/config.json
  src/unit-test/test.py
Labels: type: enhancement, help wanted, priority: high, status : confirmed

#534 fix(speech-to-text): make stt model lazy loaded
  src/apis/audio/text/speech_to_texts/coqui_english_huge_vocab/coqui_english_huge_vocab.py
Labels: type: fix

#541 docs: add --name option to docker run
  src/howto101.md
Labels: type: documentation, priority: low, type: documentations

#542 refactor: switch from uvicorn to gunicorn
  src/env.yaml
  src/main.py
  src/run_server_prod.sh
Labels: priority: high, status : confirmed, type: refactor

#548 chore: increase default timeout delay from 600s to 1200s
  src/run_server_prod.sh
Labels: priority: critical, status : confirmed, type: chore

#552 ci(Mergify): configuration update
  .mergify.yml
Labels: type: ci

#545 refactor(compose): increase nb gunicorn workers to 4
  src/docker-compose.yaml
Labels: priority: high, status : confirmed, type: refactor

#547 refactor: remove the 'tooltip' value in task description
  src/apis/audio/text/speech_to_text.py
  src/apis/image/image/background-removal.py
  src/apis/image/image/colorization.py
  src/apis/image/image/face-bluring.py
  src/apis/image/image/super-resolution.py
  src/apis/image/image/uncolorization.py
  src/apis/image/text/asciify.py
  src/apis/image/text/classification.py
  src/apis/image/text/ocr.py
  src/apis/text/text/autocorrect.py
  src/apis/text/text/boolean-question-generation.py
  src/apis/text/text/dependency-tracking.py
  src/apis/text/text/emotion-recognition.py
  src/apis/text/text/hate-speech-detection.py
  src/apis/text/text/intent-classification.py
  src/apis/text/text/keyword-extraction.py
  src/apis/text/text/language-detection.py
  src/apis/text/text/language-generation.py
  src/apis/text/text/named-entity-recognition.py
  src/apis/text/text/next-sentence-prediction.py
  src/apis/text/text/next-word-prediction.py
  src/apis/text/text/plural.py
  src/apis/text/text/programming-language-generation.py
  src/apis/text/text/programming-language-identification.py
  src/apis/text/text/question-answering.py
  src/apis/text/text/sentence-pair-modeling.py
  src/apis/text/text/sentence-paraphraser.py
  src/apis/text/text/sentiment-analysis.py
  src/apis/text/text/similarity.py
  src/apis/text/text/summarization.py
  src/apis/text/text/translation.py
  src/apis/text/text/transliteration.py
  src/apis/text/text/word-alignment.py
  src/apis/video/video/frame-interpolation.py
  src/scaffold-model.py
Labels: priority: low, status : confirmed, type: refactor

#543 fix(api): send and unpack correct input files in requests
  src/api_utils/gladia_api_utils/submodules.py
  src/unit-test/test.py
Labels: help wanted, priority: critical, status : confirmed, type: fix

#554 fix(api): force input to be interpreted as a json in body
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: fix

#557 feat(test): reorder the tests, passing the faster in first
  src/unit-test/test.py
Labels: type: enhancement

#563 perf(dockerfile): dependencies run before importing src (#537)
  src/gpu.Dockerfile
Labels: ci: ready-to-merge, type: performance

#564 ci(docker): promote latest (prepare push to DH)
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-dh-push.yml
Labels: type: ci, ci: ready-to-merge

#560 feat(logger): add StreamHandler to output on stdout
  src/api_utils/gladia_api_utils/__init__.py
  src/main.py
Labels: type: enhancement, priority: medium, ci: ready-to-merge

#567 ci(various): remove test retry and change docker trigger
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-dh-push.yml
Labels: type: ci

#562 feat(test): add default models tag to test
  src/unit-test/test.py
Labels: type: enhancement, ci: ready-to-merge

#566 refactor(api): more uniform speech to text api name
  src/apis/audio/text/audio-transcription.py
  src/apis/audio/text/audio-transcriptions/.metadata.json
  src/apis/audio/text/audio-transcriptions/__init__.py
  src/apis/audio/text/audio-transcriptions/coqui_english_huge_vocab/.metadata.json
  src/apis/audio/text/audio-transcriptions/coqui_english_huge_vocab/__init__.py
  src/apis/audio/text/audio-transcriptions/coqui_english_huge_vocab/coqui_english_huge_vocab.py
Labels: type: refactor

#565 refactor(api): clear the code and add missing input message
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/text/text/similarity.py
Labels: type: refactor, ci: ready-to-merge

#571 refactor(api): move params to form data and remove default value
  src/api_utils/gladia_api_utils/body_param_factory.py
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/image/text/ocr.py
  src/apis/text/text/similarity.py
  src/env.yaml
  src/unit-test/test.py
Labels: help wanted, priority: critical, status : confirmed, type: refactor

#570 fix(nlptown-bert-base-multilingual-uncased-sentiment): unify output format to {'label':str, 'score':float}
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
Labels: priority: low, type: fix, ci: ready-to-merge

#576 fix(colorization): check which GPU is available in colorization task
  src/api_utils/gladia_api_utils/system.py
  src/apis/image/image/colorizations/deoldify-artistic/deoldify-artistic.py
  src/apis/image/image/colorizations/deoldify-stable/deoldify-stable.py
Labels: type: fix

#578 ci(test): test status
  .github/workflows/gladia-builder.yml
Labels: type: ci

#580 docs(quality_gate): add quality_gate badge to readme
  README.md
Labels: type: documentation

#587 fix(system): get_available_gpu_ids & get_random_available_gpu_id are now usable
  src/api_utils/gladia_api_utils/system.py
  src/apis/image/image/colorizations/deoldify-artistic/deoldify-artistic.py
  src/apis/image/image/colorizations/deoldify-stable/deoldify-stable.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#575 fix(submodules): handle the logs of the different processes
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: critical, type: fix, ci: ready-to-merge

#584 ci(docker,deploy): use gladia registry to store PR builds, deploy aipi
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-dh-push.yml
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#586 fix: files are now requested using the File constructor instead of Form
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#589 docs(template): fix typo in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: documentation, priority: low, status : confirmed, ci: ready-to-merge

#573 refactor(api_utils): removed unused code in _open() function
  src/api_utils/gladia_api_utils/io.py
Labels: type: refactor

#583 refactor(model-description): change 'default' value by 'example' value
  src/api_utils/gladia_api_utils/body_param_factory.py
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/audio/text/audio-transcription.py
  src/apis/image/image/background-removal.py
  src/apis/image/image/colorization.py
  src/apis/image/image/face-bluring.py
  src/apis/image/image/super-resolution.py
  src/apis/image/image/uncolorization.py
  src/apis/image/text/asciify.py
  src/apis/image/text/classification.py
  src/apis/image/text/ocr.py
  src/apis/text/text/autocorrect.py
  src/apis/text/text/boolean-question-generation.py
  src/apis/text/text/dependency-tracking.py
  src/apis/text/text/emotion-recognition.py
  src/apis/text/text/hate-speech-detection.py
  src/apis/text/text/intent-classification.py
  src/apis/text/text/keyword-extraction.py
  src/apis/text/text/language-detection.py
  src/apis/text/text/language-generation.py
  src/apis/text/text/named-entity-recognition.py
  src/apis/text/text/next-sentence-prediction.py
  src/apis/text/text/next-word-prediction.py
  src/apis/text/text/plural.py
  src/apis/text/text/programming-language-generation.py
  src/apis/text/text/programming-language-identification.py
  src/apis/text/text/question-answering.py
  src/apis/text/text/sentence-pair-modeling.py
  src/apis/text/text/sentence-paraphraser.py
  src/apis/text/text/sentiment-analysis.py
  src/apis/text/text/similarity.py
  src/apis/text/text/summarization.py
  src/apis/text/text/translation.py
  src/apis/text/text/transliteration.py
  src/apis/text/text/word-alignment.py
  src/apis/video/video/frame-interpolation.py
  src/unit-test/test.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge

#595 feat(infra): Lauching script managing modes with only fastapi server launch for production
  .github/workflows/gladia-latest-deploy.yml
  src/README.md
  src/gpu.Dockerfile
  src/howto101.md
  src/run_server.sh
  src/run_server_prod.sh
Labels: type: enhancement, ci: ready-to-merge

#599 ci(base): prepare gladia base image
  .github/workflows/gladia-base-builder.yml
  .github/workflows/gladia-builder.yml
Labels: type: ci

#598 feat(api): Task can have default values for certain params in the Swagger
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/audio/text/audio-transcription.py
  src/apis/image/text/classification.py
  src/apis/image/text/ocr.py
  src/apis/text/text/emotion-recognition.py
  src/apis/text/text/plural.py
  src/apis/text/text/summarization.py
Labels: type: enhancement, ci: ready-to-merge

#600 ci(workflow): split linter and builder
  .github/workflows/gladia-base-builder.yml
  .github/workflows/gladia-builder.yml
  .github/workflows/pr-linter.yml
Labels: type: ci

#601 ci(base): dockerfile
  .github/workflows/gladia-builder.yml
  src/base.Dockerfile
Labels: type: ci

#602 ci(Mergify): configuration update
  .github/mergify.yml
Labels: type: ci

#607 refactor(api): reduce number of worker from 4 to 2
  src/docker-compose.yaml
Labels: priority: critical, status : confirmed, type: refactor, ci: ready-to-merge

#614 build: update fastapi version to use fork
  src/env.yaml
Labels: type: dependencies, priority: medium, status : confirmed, ci: ready-to-merge

#610 feat(image-generation): add image-generation to Gladia
  src/apis/text/image/__init__.py
  src/apis/text/image/image-generation-models/__init__.py
  src/apis/text/image/image-generation-models/stable-diffusion/.metadata.json
  src/apis/text/image/image-generation-models/stable-diffusion/__init__.py
  src/apis/text/image/image-generation-models/stable-diffusion/env.yaml
  src/apis/text/image/image-generation-models/stable-diffusion/stable-diffusion.py
  src/apis/text/image/image-generation-models/stable-diffusion/unsafe.png
  src/apis/text/image/image-generation.py
  src/gpu.Dockerfile
Labels: type: enhancement, type: new model, priority: high, status : confirmed, ci: ready-to-merge

#615 docs(readme): add badges
  README.md
Labels: type: documentation, ci: ready-to-merge

#617 fix(create_custom_envs): fix missing formatting in string
  src/tools/venv-builder/create_custom_envs.py
Labels: status : confirmed, type: fix, ci: ready-to-merge

#620 fix(base.Dockerfile): fix missing unzip
  src/base.Dockerfile
Labels: priority: high, status : confirmed, ci: ready-to-merge

#621 fix(submodule): add missing log.debug for subprocess outputs
  src/api_utils/gladia_api_utils/submodules.py
Labels: status : confirmed, type: fix, ci: ready-to-merge

#631 fix(image-generation): add default values
  src/apis/text/image/image-generation.py
Labels: type: fix, ci: ready-to-merge

#628 feat: SecretManager
  src/api_utils/gladia_api_utils/__init__.py
  src/api_utils/gladia_api_utils/secret_management.py
  src/apis/text/image/image-generation-models/stable-diffusion/stable-diffusion.py
  src/gpu.Dockerfile
Labels: type: enhancement, priority: medium, status : confirmed, ci: ready-to-merge

#625 fix(submodule): set exec path for subprocess
  src/api_utils/gladia_api_utils/run_process.py
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#639 ci(gladia-builder.yml): enable force no-cache builds
  .github/workflows/gladia-builder.yml
Labels: priority: high, type: ci, ci: ready-to-merge, ci: force-no-cache

#642 ci(gladia-builder.yml): fix space escape
  .github/workflows/gladia-builder.yml
Labels: type: ci

#623 fix(file_management): exclude models files from being detected as archive
  src/api_utils/gladia_api_utils/file_management.py
  src/api_utils/gladia_api_utils/model_management.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#636 fix(main): lazy import subprocess env
  src/main.py
Labels: priority: critical, type: fix, ci: ready-to-merge

#645 ci(gladia-latest-deploy): fix typo
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci

#646 feat(test): use _examples value to test endpoints with urlfile
  src/apis/audio/text/audio-transcription.py
  src/unit-test/test.py
Labels: type: enhancement, ci: ready-to-merge

#652 refactor(ner): remove unused param
  src/apis/text/text/named-entity-recognition-models/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
Labels: type: refactor, ci: ready-to-merge

#651 refactor(subprocesses): refactor all subprocesses code base to handle lazy loading
  src/apis/image/image/background-removal-models/mobilenet/env.yaml
  src/apis/image/image/background-removal-models/xception/env.yaml
  src/apis/image/image/colorization-models/deoldify-artistic/deoldify-artistic.py
  src/apis/image/image/colorization-models/deoldify-stable/deoldify-stable.py
  src/apis/image/image/face-bluring-models/ageitgey/ageitgey.py
  src/apis/image/image/super-resolution-models/.idealo-psnr-small/.metadata.json
  src/apis/image/image/super-resolution-models/.idealo-psnr-small/__init__.py
  src/apis/image/image/super-resolution-models/.idealo-psnr-small/env.yaml
  src/apis/image/image/super-resolution-models/.idealo-psnr-small/idealo-psnr-small.py
  src/apis/image/image/super-resolution-models/latent-sr/latent_sr.py
  src/apis/image/text/ocr-models/easy-ocr/easy-ocr.py
  src/apis/image/text/ocr-models/tesseract-default/tesseract-default.py
  src/apis/image/text/ocr-models/tesseract-denoising/tesseract-denoising.py
  src/apis/text/text/language-detection-models/toftrup-etal-2021/toftrup-etal-2021.py
  src/apis/text/text/question-answering-models/deepset-roberta-base-squad2/deepset-roberta-base-squad2.py
  src/apis/text/text/question-answering-models/deepset_bert-base-cased-squad2/env.yaml
  src/apis/text/text/question-answering-models/mfeb-albert-xxlarge-v2-squad2/mfeb-albert-xxlarge-v2-squad2.py
  src/apis/text/text/question-answering-models/mrm8488-bert-tiny-5-finetuned-squadv2/mrm8488-bert-tiny-5-finetuned-squadv2.py
  src/apis/text/text/sentiment-analysis-models/distilbert-base-uncased-finetuned-sst-2-english/distilbert-base-uncased-finetuned-sst-2-english.py
  src/apis/text/text/sentiment-analysis-models/distilbert-base-uncased/distilbert-base-uncased.py
  src/apis/text/text/sentiment-analysis-models/distilbert-base-uncased/env.yaml
Labels: type: refactor, ci: ready-to-merge

#650 refactor(submodule): make the model list outputs in alpha order
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: low, type: refactor, ci: ready-to-merge

#653 docs(readme): remove CI section
  README.md
Labels: type: documentation, ci: ready-to-merge

#654 fix(truecaser): add truecase to most NLP for more accuracy
  src/apis/text/text/autocorrect-models/flexudy-t5-base-multi-sentence-doctor/flexudy-t5-base-multi-sentence-doctor.py
  src/apis/text/text/emotion-recognition-models/mrm8488-t5-base-finetuned-emotion/mrm8488-t5-base-finetuned-emotion.py
  src/apis/text/text/hate-speech-detection-models/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-MiniLM-L6-v2/keybert-paraphrase-MiniLM-L6-v2.py
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-multilingual-MiniLM-L12-v2/keybert-paraphrase-multilingual-MiniLM-L12-v2.py
  src/apis/text/text/language-generation-models/EleutherAI-gpt-neo-2_7B/EleutherAI-gpt-neo-2_7B.py
  src/apis/text/text/named-entity-recognition-models/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
  src/apis/text/text/question-answering-models/deepset-roberta-base-squad2/deepset-roberta-base-squad2.py
  src/apis/text/text/question-answering-models/deepset_bert-base-cased-squad2/deepset_bert-base-cased-squad2.py
  src/apis/text/text/question-answering-models/distilbert-base-cased-distilled-squad/distilbert-base-cased-distilled-squad.py
  src/apis/text/text/question-answering-models/mfeb-albert-xxlarge-v2-squad2/mfeb-albert-xxlarge-v2-squad2.py
  src/apis/text/text/question-answering-models/mrm8488-bert-tiny-5-finetuned-squadv2/mrm8488-bert-tiny-5-finetuned-squadv2.py
  src/apis/text/text/sentence-paraphraser-models/ramsrigouthamg-t5-large-paraphraser-diverse-high-quality/ramsrigouthamg-t5-large-paraphraser-diverse-high-quality.py
  src/apis/text/text/sentiment-analysis-models/distilbert-base-uncased-finetuned-sst-2-english/distilbert-base-uncased-finetuned-sst-2-english.py
  src/apis/text/text/sentiment-analysis-models/distilbert-base-uncased-finetuned-sst-2-english/env.yaml
  src/apis/text/text/sentiment-analysis-models/distilbert-base-uncased/distilbert-base-uncased.py
  src/apis/text/text/sentiment-analysis-models/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
  src/apis/text/text/sentiment-analysis-models/zero-shot-classification-facebook-bart-large-mnli/zero-shot-classification-facebook-bart-large-mnli.py
  src/env.yaml
  src/gpu.Dockerfile
  src/run_server.sh
Labels: type: fix, ci: ready-to-merge

#655 fix(gladia-builder): put back missing comments
  .github/workflows/gladia-builder.yml
Labels: type: fix, ci: ready-to-merge

#657 fix(gpu.Dockerfile): add TF_CPP_MIN_LOG_LEVEL=2 for less verbosity
  src/gpu.Dockerfile
Labels: type: fix

#658 ci(gladia-builder): add non breaking test capability
  .github/workflows/gladia-builder.yml
Labels: type: ci, ci: ready-to-merge, ci: test-continue-when-fail

#659 fix(api_utils): make both loggers go to the same output file via the config file
  src/api_utils/gladia_api_utils/__init__.py
Labels: type: fix, ci: ready-to-merge

#656 fix(triton_port): move port out of TRITON_SERVER_URL using TRITON_SERVER_PORT_HTTP
  .github/workflows/gladia-latest-deploy.yml
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/docker-compose.yaml
Labels: type: fix, ci: ready-to-merge

#665 fix(ci): add push to docker hub of the gladia-base
  .github/workflows/gladia-base-builder.yml
Labels: priority: critical, ci: ready-to-merge

#664 feat(translation): add translation model
  src/apis/text/text/translation-models/__init__.py
  src/apis/text/text/translation-models/facebook-nllb-200-distilled-600M/.metadata.json
  src/apis/text/text/translation-models/facebook-nllb-200-distilled-600M/__init__.py
  src/apis/text/text/translation-models/facebook-nllb-200-distilled-600M/facebook-nllb-200-distilled-600M.py
  src/apis/text/text/translation.py
Labels: type: enhancement, ci: ready-to-merge

#669 fix(TorchvisionModelHelper): convert RGBA to RGB
  src/api_utils/gladia_api_utils/TorchvisionModelHelper.py
  src/apis/image/text/classification-models/mnasnet0_5/mnasnet0_5.py
  src/apis/image/text/classification-models/mnasnet0_75/mnasnet0_75.py
  src/apis/image/text/classification-models/mnasnet1_0/mnasnet1_0.py
  src/apis/image/text/classification-models/mnasnet1_3/mnasnet1_3.py
Labels: type: fix, ci: ready-to-merge

#662 fix(gpu.Dockerfile): align GPU ID for TORCH ORDER
  src/gpu.Dockerfile
Labels: type: fix, ci: ready-to-merge

#663 fix(apis): rewrite format to follow Open API datatypes
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/audio/text/audio-transcription.py
  src/apis/image/text/asciify.py
  src/apis/image/text/classification.py
  src/apis/image/text/ocr.py
  src/apis/text/image/image-generation.py
  src/apis/text/text/autocorrect.py
  src/apis/text/text/boolean-question-generation.py
  src/apis/text/text/dependency-tracking.py
  src/apis/text/text/emotion-recognition.py
  src/apis/text/text/hate-speech-detection.py
  src/apis/text/text/intent-classification.py
  src/apis/text/text/keyword-extraction.py
  src/apis/text/text/language-detection.py
  src/apis/text/text/language-generation.py
  src/apis/text/text/named-entity-recognition.py
  src/apis/text/text/next-sentence-prediction.py
  src/apis/text/text/next-word-prediction.py
  src/apis/text/text/plural.py
  src/apis/text/text/programming-language-generation.py
  src/apis/text/text/programming-language-identification.py
  src/apis/text/text/question-answering.py
  src/apis/text/text/sentence-pair-modeling.py
  src/apis/text/text/sentence-paraphraser.py
  src/apis/text/text/sentiment-analysis.py
  src/apis/text/text/similarity.py
  src/apis/text/text/summarization.py
  src/apis/text/text/translation.py
  src/apis/text/text/transliteration.py
  src/apis/text/text/word-alignment.py
  src/gpu.Dockerfile
Labels: type: fix, ci: ready-to-merge

#675 docs(readme): add discord badge
  README.md
Labels: type: documentation, ci: ready-to-merge

#674 fix(gpu.Dockerfile): use --cwd install of cd in mamba run
  src/gpu.Dockerfile
Labels: type: fix, ci: ready-to-merge

#681 fix(TaskRouter): provides dummy header to urlopen
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#686 refactor(test): refacto test.py before adding new features
  src/unit-test/config.json
  src/unit-test/test.py
Labels: type: refactor, ci: ready-to-merge

#685 fix(autocorrect): better result without truecase
  src/apis/text/text/autocorrect-models/flexudy-t5-base-multi-sentence-doctor/flexudy-t5-base-multi-sentence-doctor.py
Labels: type: fix, ci: ready-to-merge

#682 refactor(run_server): add breaklines to command
  src/run_server.sh
Labels: type: refactor, ci: ready-to-merge

#688 fix(background_removal): change default example
  src/apis/image/image/background-removal.py
Labels: type: fix, ci: ready-to-merge
