Repository gladiaio/gladia, pull requests merged in 2022-06, with the labels that each got.

#225 Set response media_type accordingly to output modality
  src/api_utils/gladia_api_utils/responses.py
  src/api_utils/gladia_api_utils/submodules.py
Labels: enhancement, fix, task-routeur

#213 fix bug test and modify Readme for bad localhost arg in test.py and b…
  README.md
  src/unit-test/test.py
Labels: good first issue, fix

#226 Delete empty task initializers
  src/apis/image/video/interpolation.py
  src/apis/text/text/sentence-chunking.py
Labels: enhancement

#232 Remove Cmake local install
  src/gpu.Dockerfile
Labels: enhancement, docker

#238 Feat: Allows the user to build one or multiple specific env(s)
  src/venv-builder/create_custom_envs.py
Labels: enhancement

#243 Docs: create contributing
  CONTRIBUTING.md
Labels: documentation

#242 Update dockerfile accordingly to the new env/package manager
  src/gpu.Dockerfile
Labels: docker

#253 docs: add continue option to tests in case some fail
  README.md
Labels: documentation

#252 fix curl ref in docker
  src/gpu.Dockerfile
Labels: fix, docker

#268 fix(text/text/similarity): replace sentences default values by empty strings
  src/apis/text/text/similarity.py
Labels: fix, Input: Text 💬, Output: Text 💬

#275 chore: add pre commit hooks to the project
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
Labels: tools

#277 Doc add badge black
  README.md
Labels: documentation
