Repository gladiaio/gladia, pull requests merged in 2022-07, with the labels that each got.

#285 feat/add capability to generate a deploy message based on a commit
  src/tools/run_ci_pr.py
Labels: type: enhancement, priority: low, status : confirmed

#286 feat/add-image-image-classification-resnet50
  src/apis/image/text/classification.py
  src/apis/image/text/classifications/__init__.py
  src/apis/image/text/classifications/resnet50/__init__.py
  src/apis/image/text/classifications/resnet50/resnet50.py
Labels: type: enhancement

#290 feat/add image-image-classification-alexnet
  src/apis/image/text/classifications/alexnet/__init__.py
  src/apis/image/text/classifications/alexnet/alexnet.py
Labels: type: enhancement

#297 feat/add image to text classification densenet121
  src/apis/image/text/classifications/densenet121/__init__.py
  src/apis/image/text/classifications/densenet121/densenet121.py
Labels: type: new model

#292 feat/add image to text classification convnext_large
  src/apis/image/text/classifications/convnext_large/__init__.py
  src/apis/image/text/classifications/convnext_large/convnext_large.py
Labels: type: new model

#306 Feat/image text classification efficientnet b6
  src/apis/image/text/classifications/densenet161/__init__.py
  src/apis/image/text/classifications/densenet161/densenet161.py
  src/apis/image/text/classifications/densenet169/__init__.py
  src/apis/image/text/classifications/densenet169/densenet169.py
  src/apis/image/text/classifications/densenet201/__init__.py
  src/apis/image/text/classifications/densenet201/densenet201.py
  src/apis/image/text/classifications/efficientnet_b0/__init__.py
  src/apis/image/text/classifications/efficientnet_b0/efficientnet_b0.py
  src/apis/image/text/classifications/efficientnet_b1_v1/__init__.py
  src/apis/image/text/classifications/efficientnet_b1_v1/efficientnet_b1_v1.py
  src/apis/image/text/classifications/efficientnet_b1_v2/__init__.py
  src/apis/image/text/classifications/efficientnet_b1_v2/efficientnet_b1_v2.py
  src/apis/image/text/classifications/efficientnet_b2/__init__.py
  src/apis/image/text/classifications/efficientnet_b2/efficientnet_b2.py
  src/apis/image/text/classifications/efficientnet_b4/__init__.py
  src/apis/image/text/classifications/efficientnet_b4/efficientnet_b4.py
  src/apis/image/text/classifications/efficientnet_b5/__init__.py
  src/apis/image/text/classifications/efficientnet_b5/efficientnet_b5.py
  src/apis/image/text/classifications/efficientnet_b6/__init__.py
  src/apis/image/text/classifications/efficientnet_b6/efficientnet_b6.py
Labels: type: new model

#296 feat/add image to text classification densenet161
  src/apis/image/text/classifications/densenet121/__init__.py
  src/apis/image/text/classifications/densenet121/densenet121.py
Labels: type: new model

#293 feat/add image to text classification convnext_base
  src/apis/image/text/classifications/convnext_base/__init__.py
  src/apis/image/text/classifications/convnext_base/convnext_base.py
Labels: type: new model

#294 feat/add image to text classification convnext_small
  src/apis/image/text/classifications/convnext_small/__init__.py
  src/apis/image/text/classifications/convnext_small/convnext_small.py
Labels: type: new model

#295 feat/add image to text classification convnext_tiny
  src/apis/image/text/classifications/convnext_tiny/__init__.py
  src/apis/image/text/classifications/convnext_tiny/convnext_tiny.py
Labels: type: new model

#303 Feat/image text classification efficientnet b3
  src/apis/image/text/classifications/efficientnet_b3/__init__.py
  src/apis/image/text/classifications/efficientnet_b3/efficientnet_b3.py
Labels: type: new model

#312 feat(model:efficientnet_b7): added image to text efficientnet_b7
  src/apis/image/text/classifications/efficientnet_b7/__init__.py
  src/apis/image/text/classifications/efficientnet_b7/efficientnet_b7.py
Labels: type: new model

#311 Feat/image text classification efficientnet v2 m&s
  src/apis/image/text/classifications/efficientnet_v2_m/__init__.py
  src/apis/image/text/classifications/efficientnet_v2_m/efficientnet_v2_m.py
  src/apis/image/text/classifications/efficientnet_v2_s/__init__.py
  src/apis/image/text/classifications/efficientnet_v2_s/efficientnet_v2_s.py
Labels: type: new model

#323 fix(run_ci_pr): fix return of the smallest PR associated to a commit
  src/tools/run_ci_pr.py
Labels: type: bug

#329 fix(image-classification): fix missing top_k param in classification abstract class
  src/apis/image/text/classification.py
Labels: type: bug

#331 fix(run_ci_pr): add the support for parenthesis commit formatting in deploy message
  src/tools/run_ci_pr.py
Labels: type: bug

#315 Feat/image text classification mnasnet0 5
  src/apis/image/text/classifications/mnasnet0_5/__init__.py
  src/apis/image/text/classifications/mnasnet0_5/mnasnet0_5.py
Labels: type: new model

#317 Feat/image text classification mnasnet1 0
  src/apis/image/text/classifications/mnasnet1_0/__init__.py
  src/apis/image/text/classifications/mnasnet1_0/mnasnet1_0.py
Labels: type: new model

#322 feat: TorchvisionModel wrapper
  src/api_utils/gladia_api_utils/TorchvisionModel.py
  src/api_utils/gladia_api_utils/__init__.py
  src/apis/image/text/classifications/mnasnet0_5/mnasnet0_5.py
Labels: type: enhancement, priority: medium, status : confirmed

#338 GET requests now return a dict instead of a list
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: enhancement, priority: medium, status : confirmed

#333 fix(run_ci_pr): remove. pre-commit bot from deploy message
  src/tools/run_ci_pr.py
Labels: type: bug

#342 chore(pre-commit): add commitizen check to pre-commit hooks
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: type: chore

#343 feat(mobilenet_v2): add mobilenet_v2_v1 and mobilenet_v2_v2 to image/text/classification
  src/apis/image/text/classifications/mobilenet_v2_v1/__init__.py
  src/apis/image/text/classifications/mobilenet_v2_v1/mobilenet_v2_v1.py
  src/apis/image/text/classifications/mobilenet_v2_v2/__init__.py
  src/apis/image/text/classifications/mobilenet_v2_v2/mobilenet_v2_v2.py
Labels: type: bug, type: new model

#344 feat(mobilenet_v3): add mobilenet_v3_small, mobilenet_v3_large_v1 and mobilenet_v3_large_v2 to image/text/classification
  src/apis/image/text/classifications/mobilenet_v3_large_v1/__init__.py
  src/apis/image/text/classifications/mobilenet_v3_large_v1/mobilenet_v3_large_v1.py
  src/apis/image/text/classifications/mobilenet_v3_large_v2/__init__.py
  src/apis/image/text/classifications/mobilenet_v3_large_v2/mobilenet_v3_large_v2.py
  src/apis/image/text/classifications/mobilenet_v3_small/__init__.py
  src/apis/image/text/classifications/mobilenet_v3_small/mobilenet_v3_small.py
Labels: type: new model

#346 feat(regnet_x_16gf): add regnet_x_16gf_v1 and regnet_x_16gf_v2 to image/text/classification
  src/apis/image/text/classifications/regnet_x_16gf_v1/__init__.py
  src/apis/image/text/classifications/regnet_x_16gf_v1/regnet_x_16gf_v1.py
  src/apis/image/text/classifications/regnet_x_16gf_v2/__init__.py
  src/apis/image/text/classifications/regnet_x_16gf_v2/regnet_x_16gf_v2.py
Labels: type: new model

#358 feat(resnet): add resnet50_v1 to image/text/classification
  src/apis/image/text/classifications/resnet50_v1/__init__.py
  src/apis/image/text/classifications/resnet50_v1/resnet50_v1.py
  src/apis/image/text/classifications/resnet50_v2/__init__.py
  src/apis/image/text/classifications/resnet50_v2/resnet50_v2.py
Labels: type: new model

#359 feat(resnet34): add resnet34 to image/text/classification
  src/apis/image/text/classifications/resnet34/__init__.py
  src/apis/image/text/classifications/resnet34/resnet34.py
Labels: type: new model

#378 feat(vgg16_bn): add VGG16_BN to image/text/classification
  src/apis/image/text/classifications/vgg16_bn/__init__.py
  src/apis/image/text/classifications/vgg16_bn/vgg16_bn.py
Labels: type: new model

#376 feat(swin_b): add Swin_B to image/text/classification
  src/apis/image/text/classifications/swin_b/__init__.py
  src/apis/image/text/classifications/swin_b/swin_b.py
Labels: type: new model

#375 feat(swin_s): add Swin_S to image/text/classification
  src/apis/image/text/classifications/swin_s/__init__.py
  src/apis/image/text/classifications/swin_s/swin_s.py
Labels: type: new model

#379 feat(wide_resnet101_2): add wide_resnet101_2 to image/text/classifica…
  src/apis/image/text/classifications/wide_resnet101_2_v1/__init__.py
  src/apis/image/text/classifications/wide_resnet101_2_v1/wide_resnet101_2_v1.py
  src/apis/image/text/classifications/wide_resnet101_2_v2/__init__.py
  src/apis/image/text/classifications/wide_resnet101_2_v2/wide_resnet101_2_v2.py
Labels: type: new model

#377 feat(vgg13): add VGG13 to image/text/classification
  src/apis/image/text/classifications/vgg13/__init__.py
  src/apis/image/text/classifications/vgg13/vgg13.py
Labels: type: new model

#371 feat(vgg13_bn): add VGG13_BN to image/text/classification
  src/apis/image/text/classifications/vgg13_bn/__init__.py
  src/apis/image/text/classifications/vgg13_bn/vgg13_bn.py
Labels: type: new model

#370 feat(vgg19_bn): add VGG19_BN to image/text/classification
  src/apis/image/text/classifications/vgg19_bn/__init__.py
  src/apis/image/text/classifications/vgg19_bn/vgg19_bn.py
Labels: type: new model

#382 fix(classification): switch default model to alexnet
  src/apis/image/text/classification.py
Labels: type: bug

#383 fix(regnet_x_3_2gf_v2): fix regnet_x_3_2gf_v2 file references
  src/apis/image/text/classifications/regnet_x_3_2gf_v2/regnet_x_3_2gf_v2.py
Labels: type: bug, priority: hight, status : confirmed

#380 fix(run_ci_pr): add committizen convention support to CI checks
  src/tools/run_ci_pr.py
Labels: priority: medium, status : confirmed, type: chore

#372 feat(vgg11): add VGG11 to image/text/classification
  src/apis/image/text/classifications/vgg11/__init__.py
  src/apis/image/text/classifications/vgg11/vgg11.py
Labels: type: new model, priority: low, status : confirmed

#373 feat(vgg11_bn): add VGG11_BN to image/text/classification
  src/apis/image/text/classifications/vgg11_bn/__init__.py
  src/apis/image/text/classifications/vgg11_bn/vgg11_bn.py
Labels: type: new model, priority: low, status : confirmed

#374 feat(swin_t): add Swin_T to image/text/classification
  src/apis/image/text/classifications/swin_t/__init__.py
  src/apis/image/text/classifications/swin_t/swin_t.py
Labels: type: new model, priority: low, status : confirmed

#368 feat(vit_b_32): add ViT_B_32 to image/text/classification
  src/apis/image/text/classifications/vit_b_32/__init__.py
  src/apis/image/text/classifications/vit_b_32/vit_b_32.py
Labels: type: new model, priority: low, status : confirmed

#367 feat(vit_l_32): add ViT_L_32 to image/text/classification
  src/apis/image/text/classifications/vit_l_32/__init__.py
  src/apis/image/text/classifications/vit_l_32/vit_l_32.py
Labels: type: new model, priority: low, status : confirmed

#365 feat(shufflenet_v2_x1_0): add shufflenet_v2_x1_0 to image/text/classi…
  src/apis/image/text/classifications/shufflenet_v2_x1_0/__init__.py
  src/apis/image/text/classifications/shufflenet_v2_x1_0/shufflenet_v2_x1_0.py
Labels: type: new model, priority: low, status : confirmed

#364 feat(shufflenet_v2_x1_5): add shufflenet_v2_x1_5 to image/text/classi…
  src/apis/image/text/classifications/shufflenet_v2_x1_5/__init__.py
  src/apis/image/text/classifications/shufflenet_v2_x1_5/shufflenet_v2_x1_5.py
Labels: type: new model, priority: low, status : confirmed

#361 feat(resnet18): add resnet18 to image/text/classification
  src/apis/image/text/classifications/resnet18/__init__.py
  src/apis/image/text/classifications/resnet18/resnet18.py
Labels: type: new model, priority: low, status : confirmed

#360 feat(squeezenet1_1): add squeezenet1_1 to image/text/classification
  src/apis/image/text/classifications/squeezenet1_1/__init__.py
  src/apis/image/text/classifications/squeezenet1_1/squeezenet1_1.py
Labels: type: new model, priority: low, status : confirmed

#362 feat(squeezenet1_0): add squeezenet1_0 to image/text/classification
  src/apis/image/text/classifications/squeezenet1_0/__init__.py
  src/apis/image/text/classifications/squeezenet1_0/squeezenet1_0.py
Labels: type: new model, priority: low, status : confirmed

#388 feat(vit_h_14): add vit_h_14 to image/text/classification
  src/apis/image/text/classifications/vit_h_14_swag_e2e_v1/__init__.py
  src/apis/image/text/classifications/vit_h_14_swag_e2e_v1/vit_h_14_swag_e2e_v1.py
  src/apis/image/text/classifications/vit_h_14_swag_linear_v1/__init__.py
  src/apis/image/text/classifications/vit_h_14_swag_linear_v1/vit_h_14_swag_linear_v1.py
Labels: type: new model

#387 feat(vit_b_16): add vit_b_16 to image/text/classification
  src/apis/image/text/classifications/vit_b_16_swag_e2e_v1/__init__.py
  src/apis/image/text/classifications/vit_b_16_swag_e2e_v1/vit_b_16_swag_e2e_v1.py
  src/apis/image/text/classifications/vit_b_16_swag_linear_v1/__init__.py
  src/apis/image/text/classifications/vit_b_16_swag_linear_v1/vit_b_16_swag_linear_v1.py
  src/apis/image/text/classifications/vit_b_16_v1/__init__.py
  src/apis/image/text/classifications/vit_b_16_v1/vit_b_16_v1.py
Labels: type: new model, priority: low, status : confirmed

#389 feat(vgg16): add vgg16 to image/text/classification
  src/apis/image/text/classifications/vgg16_v1/__init__.py
  src/apis/image/text/classifications/vgg16_v1/vgg16_v1.py
Labels: type: new model, priority: low, status : confirmed

#391 feat(resnext50_32x4d): add resnext50_32x4d to image/text/classification
  src/apis/image/text/classifications/resnext50_32x4d_v1/__init__.py
  src/apis/image/text/classifications/resnext50_32x4d_v1/resnext50_32x4d_v1.py
  src/apis/image/text/classifications/resnext50_32x4d_v2/__init__.py
  src/apis/image/text/classifications/resnext50_32x4d_v2/resnext50_32x4d_v2.py
Labels: type: new model

#351 feat(regnet_x_800mf): add regnet_x_800mf_v1 and regnet_x_800mf_v2 to image/text/classification
  src/apis/image/text/classifications/regnet_x_800mf_v1/__init__.py
  src/apis/image/text/classifications/regnet_x_800mf_v1/regnet_x_800mf_v1.py
  src/apis/image/text/classifications/regnet_x_800mf_v2/__init__.py
  src/apis/image/text/classifications/regnet_x_800mf_v2/regnet_x_800mf_v2.py
Labels: type: new model, priority: low, status : confirmed

#392 feat(resnext101_64x4d): add resnext101_64x4d to image/text/classification
  src/apis/image/text/classifications/resnext101_64x4d_v1/__init__.py
  src/apis/image/text/classifications/resnext101_64x4d_v1/resnext101_64x4d_v1.py
Labels: type: new model

#395 feat(regnet_y_16gf): add regnet_y_16gf to image/text/classification
  src/apis/image/text/classifications/regnet_y_16gf_swag_e2e_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_16gf_swag_e2e_v1/regnet_y_16gf_swag_e2e_v1.py
  src/apis/image/text/classifications/regnet_y_16gf_swag_linear_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_16gf_swag_linear_v1/regnet_y_16gf_swag_linear_v1.py
  src/apis/image/text/classifications/regnet_y_16gf_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_16gf_v1/regnet_y_16gf_v1.py
  src/apis/image/text/classifications/regnet_y_16gf_v2/__init__.py
  src/apis/image/text/classifications/regnet_y_16gf_v2/regnet_y_16gf_v2.py
Labels: type: new model

#393 feat(vit_l_16): add vit_l_16 to image/text/classification
  src/apis/image/text/classifications/vit_l_16_swag_e2e_v1/__init__.py
  src/apis/image/text/classifications/vit_l_16_swag_e2e_v1/vit_l_16_swag_e2e_v1.py
  src/apis/image/text/classifications/vit_l_16_swag_linear_v1/__init__.py
  src/apis/image/text/classifications/vit_l_16_swag_linear_v1/vit_l_16_swag_linear_v1.py
  src/apis/image/text/classifications/vit_l_16_v1/__init__.py
  src/apis/image/text/classifications/vit_l_16_v1/vit_l_16_v1.py
Labels: type: new model

#396 feat(regnet_x_8gf): add regnet_x_8gf to image/text/classification
  src/apis/image/text/classifications/regnet_x_8gf_v1/__init__.py
  src/apis/image/text/classifications/regnet_x_8gf_v1/regnet_x_8gf_v1.py
  src/apis/image/text/classifications/regnet_x_8gf_v2/__init__.py
  src/apis/image/text/classifications/regnet_x_8gf_v2/regnet_x_8gf_v2.py
Labels: type: new model

#397 feat(regnet_y_128gf): add regnet_y_128gf to image/text/classification
  src/apis/image/text/classifications/regnet_y_128gf_swag_e2e_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_128gf_swag_e2e_v1/regnet_y_128gf_swag_e2e_v1.py
  src/apis/image/text/classifications/regnet_y_128gf_swag_linear_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_128gf_swag_linear_v1/regnet_y_128gf_swag_linear_v1.py
Labels: type: new model

#398 feat(regnet_y_128gf): add regnet_y_128gf to image/text/classification
  src/apis/image/text/classifications/regnet_y_128gf_swag_e2e_v1/mobilenet_v2_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_128gf_swag_e2e_v1/mobilenet_v2_v1/mobilenet_v2_v1.py
  src/apis/image/text/classifications/regnet_y_128gf_swag_linear_v1/mobilenet_v2_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_128gf_swag_linear_v1/mobilenet_v2_v1/mobilenet_v2_v1.py
Labels: type: new model

#394 feat(regnet_y_1_6gf): add regnet_y_1_6gf to image/text/classification
  src/apis/image/text/classifications/regnet_y_1_6gf_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_1_6gf_v1/regnet_y_1_6gf_v1.py
  src/apis/image/text/classifications/regnet_y_1_6gf_v2/__init__.py
  src/apis/image/text/classifications/regnet_y_1_6gf_v2/regnet_y_1_6gf_v2.py
Labels: type: new model

#390 feat(resnet152): add resnet152 to image/text/classification
  src/apis/image/text/classifications/resnet152_v1/__init__.py
  src/apis/image/text/classifications/resnet152_v1/resnet152_v1.py
  src/apis/image/text/classifications/resnet152_v2/__init__.py
  src/apis/image/text/classifications/resnet152_v2/resnet152_v2.py
Labels: type: new model, priority: low, status : confirmed

#405 fix(regnet_y_128gf_swag_e2e_v1): remove wrong regnet_y_128gf_swag_e2e_v1 subfolder
  src/apis/image/text/classifications/regnet_y_128gf_swag_e2e_v1/mobilenet_v2_v1/__init__.py
  src/apis/image/text/classifications/regnet_y_128gf_swag_e2e_v1/mobilenet_v2_v1/mobilenet_v2_v1.py
Labels: type: new model

#409 feat(TorchvisionModelHelper): add quantized support to TorchvisionModelHelper
  src/api_utils/gladia_api_utils/TorchvisionModelHelper.py
Labels: type: new model

#418 docs(gladia-server): add readme to src
  src/README.md
Labels: type: documentation

#419 fix(file_management): add support for bytes download in file_management
  src/api_utils/gladia_api_utils/file_management.py
Labels: type: bug

#424 docs(apis/readme): fix typo
  src/README.md
Labels: type: documentation

#423 feat(coqui_english_huge_vocab): add STT coqui_english_huge_vocab model
  src/api_utils/gladia_api_utils/CoquiEngineHelper.py
  src/api_utils/gladia_api_utils/file_management.py
  src/api_utils/gladia_api_utils/model_management.py
  src/apis/audio/__init__.py
  src/apis/audio/text/__init__.py
  src/apis/audio/text/speech_to_text.py
  src/apis/audio/text/speech_to_texts/__init__.py
  src/apis/audio/text/speech_to_texts/coqui_english_huge_vocab/__init__.py
  src/apis/audio/text/speech_to_texts/coqui_english_huge_vocab/coqui_english_huge_vocab.py
  src/env.yaml
  src/unit-test/test.mp3
  src/unit-test/test.py
Labels: type: new model, priority: high

#440 delete(download_active_models): as it is unused
  src/api_utils/gladia_api_utils/download_active_models.py
Labels: type: enhancement, priority: low, status : confirmed

#442 Fix(docker): trying to split into smaller layers
  src/.dockerignore
  src/gpu.Dockerfile
  src/mamba.conf
  src/venv-builder/create_custom_envs.py
Labels: type: bug, priority: critical

#441 Models pulled using .git_path are now extracted from their folder
  src/api_utils/gladia_api_utils/triton_helper/download_active_models.py
Labels: type: enhancement, priority: high, status : confirmed

#445 Switch nlptown bert base multilingual uncased sentiment model to triton
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/.git_path
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
  src/docker-compose.yaml
Labels: type: enhancement, priority: medium, status : confirmed

#453 doc(readme): add shared memory size instructions
  README.md
Labels: type: documentation, status: duplicate, priority: high

#456 Hide triton_server_url TritonClient's param into kwargs
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/apis/text/text/entity-extractions/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
  src/apis/text/text/hate-speech-detections/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
Labels: type: enhancement, priority: medium, status : confirmed

#458 delete: entity extraction task
  src/apis/text/text/entity-extraction.py
  src/apis/text/text/entity-extractions/__init__.py
  src/apis/text/text/entity-extractions/dbmdz-bert-large-cased-finetuned-conll03-english/.git_path
  src/apis/text/text/entity-extractions/dbmdz-bert-large-cased-finetuned-conll03-english/__init__.py
  src/apis/text/text/entity-extractions/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
Labels: type: enhancement, priority: medium, status : confirmed

#459 Switch NER "dbmdz bert large cased finetuned conll03 english" model to Triton
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/api_utils/gladia_api_utils/triton_helper/__init__.py
  src/api_utils/gladia_api_utils/triton_helper/data_processing.py
  src/apis/text/text/named-entity-recognitions/dbmdz-bert-large-cased-finetuned-conll03-english/.git_path
  src/apis/text/text/named-entity-recognitions/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
Labels: type: enhancement, priority: medium, status : confirmed

#471 ci(test): add capability to filter test (models or wider endpoints)
  src/unit-test/test.py
Labels: priority: low

#463 fix(sentiment-analysis): json output format
  src/apis/text/text/sentiment-analyses/distilbert-base-uncased-finetuned-sst-2-english/distilbert-base-uncased-finetuned-sst-2-english.py
  src/apis/text/text/sentiment-analyses/zero-shot-classification-facebook-bart-large-mnli/zero-shot-classification-facebook-bart-large-mnli.py
Labels: priority: high

#473 ci(test): add better test for audio
  src/unit-test/test.m4a
  src/unit-test/test.py
  src/unit-test/test.wav
Labels: priority: medium

#466 fix(text_similarities): fix output to be a json
  src/api_utils/gladia_api_utils/casting.py
  src/apis/text/text/next-word-predictions/albert-base-v2/albert-base-v2.py
  src/apis/text/text/next-word-predictions/bert-base-uncased/bert-base-uncased.py
  src/apis/text/text/next-word-predictions/distilbert-base-uncased/distilbert-base-uncased.py
  src/apis/text/text/next-word-predictions/roberta-base/roberta-base.py
  src/apis/text/text/sentiment-analyses/distilbert-base-uncased/distilbert-base-uncased.py
  src/apis/text/text/similarities/all-MiniLM-L6-v2/all-MiniLM-L6-v2.py
Labels: priority: high

#462 feat(gladia_api_utils): support command line subprocesses
  .pre-commit-config.yaml
  src/api_utils/gladia_api_utils/run_process.py
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: enhancement

#474 New language detection model : papluca_xlm-roberta-base-language-detection_tensorrt
  src/apis/text/text/language-detections/xlm-roberta-base-language-detection/.git_path
  src/apis/text/text/language-detections/xlm-roberta-base-language-detection/__init__.py
  src/apis/text/text/language-detections/xlm-roberta-base-language-detection/xlm-roberta-base-language-detection.py
Labels: type: new model, priority: medium, status : confirmed

#472 feat(dockerfile): cleaner dockerfile
  src/_dockerfile_shell.sh
  src/_entrypoint.sh
  src/apis/run_docker.sh
  src/build_and_prod
  src/build_and_push
  src/gpu.Dockerfile
  src/tools/ci/run_ci_pr.py
  src/tools/docker/_activate_current_env.sh
  src/tools/docker/clean-layer.sh
  src/tools/docker/entrypoint.sh
  src/tools/venv-builder/README.md
  src/tools/venv-builder/create_custom_envs.py
  src/tools/venv-builder/envs/audio/base.yaml
  src/tools/venv-builder/envs/audio/torchaudio.yaml
  src/tools/venv-builder/envs/common/base.yaml
  src/tools/venv-builder/envs/common/sklearn.yaml
  src/tools/venv-builder/envs/common/tensorflow.yaml
  src/tools/venv-builder/envs/common/torch.yaml
  src/tools/venv-builder/envs/image/base.yaml
  src/tools/venv-builder/envs/image/deoldify.yaml
  src/tools/venv-builder/envs/image/scikit-image.yaml
  src/tools/venv-builder/envs/image/torchvision.yaml
  src/tools/venv-builder/envs/text/base.yaml
  src/tools/venv-builder/envs/text/nltk.yaml
  src/tools/venv-builder/envs/text/transformers.yaml
  src/tools/venv-builder/envs/video/base.yaml
Labels: priority: critical

#477 feat(TritonClient): models can be preloaded
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/api_utils/gladia_api_utils/triton_helper/__init__.py
  src/api_utils/gladia_api_utils/triton_helper/helper.py
  src/apis/text/text/hate-speech-detections/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py
  src/apis/text/text/language-detections/xlm-roberta-base-language-detection/xlm-roberta-base-language-detection.py
  src/apis/text/text/named-entity-recognitions/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
  src/config.json
Labels: type: enhancement, priority: critical, status : confirmed

#478 refactor: set triton models as default ones
  src/apis/text/text/language-detection.py
  src/apis/text/text/sentiment-analysis.py
Labels: priority: high, status : confirmed

#491 feat: add all-MiniLM-L6-v2 to triton
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/apis/text/text/hate-speech-detections/Hate-speech-CNERG-dehatebert-mono-english/Hate-speech-CNERG-dehatebert-mono-english.py
  src/apis/text/text/language-detections/xlm-roberta-base-language-detection/xlm-roberta-base-language-detection.py
  src/apis/text/text/named-entity-recognitions/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
  src/apis/text/text/sentiment-analyses/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
  src/apis/text/text/similarities/all-MiniLM-L6-v2/.git_path
  src/apis/text/text/similarities/all-MiniLM-L6-v2/all-MiniLM-L6-v2.py
  src/config.json
Labels: type: enhancement
