Repository gladiaio/gladia, pull requests merged in 2022-11, with the labels that each got.

#881 fix(super-resolution): udpate rank_zero_only import
  src/apis/image/image/super-resolution-models/latent-sr/ldm/models/diffusion/ddpm.py
Labels: priority: critical, type: fix, ci: ready-to-merge

#880 feat: config can specify model
  src/main.py
Labels: type: enhancement, help wanted, priority: high, ci: ready-to-merge, ci: build-base

#884 refactor(test): set logging format
  src/pytest.ini
Labels: priority: high, type: refactor, ci: ready-to-merge

#891 ci(rollout): sequentially wait for rollout success
  .github/workflows/gladia-latest-deploy.yml
Labels: ci: ready-to-merge

#892 ci(pypi): fix push to pypi
  .github/workflows/upload-api-utils-to-pypi.yaml
Labels: type: ci, ci: ready-to-merge

#893 refactor: remove triton models
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-MiniLM-L6-v2/.git_path
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-MiniLM-L6-v2/.model_metadata.yaml
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-MiniLM-L6-v2/__init__.py
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-MiniLM-L6-v2/keybert-paraphrase-MiniLM-L6-v2.py
  src/apis/text/text/keyword-extraction.py
  src/apis/text/text/language-detection-models/xlm-roberta-base-language-detection/.git_path
  src/apis/text/text/language-detection-models/xlm-roberta-base-language-detection/.model_metadata.yaml
  src/apis/text/text/language-detection-models/xlm-roberta-base-language-detection/__init__.py
  src/apis/text/text/language-detection-models/xlm-roberta-base-language-detection/xlm-roberta-base-language-detection.py
  src/apis/text/text/language-detection.py
  src/apis/text/text/named-entity-recognition-models/dbmdz-bert-large-cased-finetuned-conll03-english/.git_path
  src/apis/text/text/named-entity-recognition-models/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
  src/apis/text/text/sentiment-analysis-models/nlptown-bert-base-multilingual-uncased-sentiment/.git_path
  src/apis/text/text/sentiment-analysis-models/nlptown-bert-base-multilingual-uncased-sentiment/.model_metadata.yaml
  src/apis/text/text/sentiment-analysis-models/nlptown-bert-base-multilingual-uncased-sentiment/__init__.py
  src/apis/text/text/sentiment-analysis-models/nlptown-bert-base-multilingual-uncased-sentiment/nlptown-bert-base-multilingual-uncased-sentiment.py
  src/apis/text/text/sentiment-analysis.py
  src/apis/text/text/similarity-models/all-MiniLM-L6-v2/.git_path
  src/apis/text/text/similarity-models/all-MiniLM-L6-v2/all-MiniLM-L6-v2.py
Labels: type: refactor, ci: ready-to-merge

#896 feat: health endpoint
  src/main.py
Labels: type: enhancement, ci: ready-to-merge

#895 refactor: move router init to api_utils
  src/api_utils/gladia_api_utils/__init__.py
  src/api_utils/gladia_api_utils/add_routes_to_router.py
  src/main.py
Labels: priority: high, type: refactor, ci: ready-to-merge

#897 ci(pypi): delegate to GH as workaround
  .github/workflows/upload-api-utils-to-pypi.yaml
Labels: type: ci, ci: ready-to-merge

#882 feat(date-cleaning): add date-cleaning
  src/apis/text/text/address-formatting.py
  src/apis/text/text/date-cleaning-models/.task_metadata.yaml
  src/apis/text/text/date-cleaning-models/__init__.py
  src/apis/text/text/date-cleaning-models/dataprep-formatter/__init__.py
  src/apis/text/text/date-cleaning-models/dataprep-formatter/dataprep-formatter.py
  src/apis/text/text/date-cleaning.py
  src/apis/text/text/language-detection-models/toftrup-etal-2021/env.yaml
  src/env.yaml
  src/tools/venv-builder/build-this-folder-env.sh
  src/tools/venv-builder/envs/common/torch.yaml
Labels: type: enhancement, ci: ready-to-merge, ci: force-build-gladia

#900 fix(health): fix health endpoint
  src/main.py
Labels: type: fix, ci: ready-to-merge

#901 feat(env.yaml): add accelerate package
  src/env.yaml
Labels: type: enhancement

#886 build(api_utils): remove huggingface_hub, transformers and uuid as deps
  src/api_utils/setup.py
Labels: type: dependencies, priority: low, status : confirmed, ci: ready-to-merge, ci: force-no-cache, ci: force-build-gladia, ci: build-base

#894 refactor: remove triton
  src/README.md
  src/base.Dockerfile
  src/config.json
  src/docker-compose.yaml
  src/env.yaml
  src/gpu.Dockerfile
  src/licenses-used.md
  src/main.py
  src/run_server.sh
  src/tools/venv-builder/envs/common/base.yaml
  src/warm_up.py
Labels: type: refactor, ci: build-base

#871 feat(speaker-diarization): add speaker diarization
  README.md
  src/apis/audio/text/speaker-diarization-models/.task_metadata.yaml
  src/apis/audio/text/speaker-diarization-models/__init__.py
  src/apis/audio/text/speaker-diarization-models/pyannote-speaker_diarization/.model_metadata.yaml
  src/apis/audio/text/speaker-diarization-models/pyannote-speaker_diarization/__init__.py
  src/apis/audio/text/speaker-diarization-models/pyannote-speaker_diarization/env.yaml
  src/apis/audio/text/speaker-diarization-models/pyannote-speaker_diarization/pyannote-speaker_diarization.py
  src/apis/audio/text/speaker-diarization.py
  src/base.Dockerfile
  src/env.yaml
  src/gpu.Dockerfile
  src/tools/venv-builder/envs/audio/base.yaml
  src/tools/venv-builder/envs/audio/torchaudio.yaml
Labels: type: enhancement, ci: ready-to-merge, ci: force-build-gladia, ci: build-base

#877 feat(speaker-gender-classification): add speaker gender classification
  src/apis/audio/text/speaker-gender-classification-models/.task_metadata.yaml
  src/apis/audio/text/speaker-gender-classification-models/__init__.py
  src/apis/audio/text/speaker-gender-classification-models/inafoss-inaSpeechSegmenter/.model_metadata.yaml
  src/apis/audio/text/speaker-gender-classification-models/inafoss-inaSpeechSegmenter/__init__.py
  src/apis/audio/text/speaker-gender-classification-models/inafoss-inaSpeechSegmenter/env.yaml
  src/apis/audio/text/speaker-gender-classification-models/inafoss-inaSpeechSegmenter/inafoss-inaSpeechSegmenter.py
  src/apis/audio/text/speaker-gender-classification.py
Labels: type: enhancement, ci: ready-to-merge, ci: force-no-cache, ci: force-build-gladia, ci: build-base

#902 refactor(api_utils): reduce logs backup to 1
  src/api_utils/gladia_api_utils/__init__.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge

#907 ci(docker): always prune old data a after successful build
  .github/workflows/gladia-builder.yml
Labels: type: ci, ci: ready-to-merge

#906 feat(run_server.sh): set cwd
  src/run_server.sh
Labels: type: enhancement, ci: ready-to-merge

#908 feat: custom envs can now be shared
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/image/image/colorization/deoldify-artistic/env.yaml
  src/apis/image/image/colorization/deoldify-stable/env.yaml
  src/tools/venv-builder/create_custom_envs.py
Labels: type: enhancement, priority: high, status : confirmed

#909 feat: venv-builder no longer double build shared custom envs
  src/tools/venv-builder/create_custom_envs.py
Labels: type: enhancement

#916 refactor(tools): remove deprecated ci/ folder
  src/tools/ci/run_ci_pr.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge

#918 refactor(tests): remove deprecated import
  src/apis/image/image/background-replacement/test_background_replacement.py
  src/apis/image/image/guided-inpainting/test_guided_inpainting.py
  src/apis/image/image/inpainting/test_inpainting.py
  src/apis/image/text/classification/test_classification.py
  src/apis/image/text/ocr/test_ocr.py
  src/apis/text/text/headline-generation/test_headline_generation.py
  src/apis/text/text/keyword-extraction/test_keyword_extraction.py
  src/apis/text/text/next-sentence-prediction/test_next_sentence_prediction.py
  src/apis/text/text/next-word-prediction/test_next_word_prediction.py
  src/apis/text/text/question-answering/test_question_answering.py
  src/apis/text/text/similarity/test_similarity.py
  src/apis/text/text/summarization/test_summarization.py
  src/apis/text/text/translation/test_translation.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge

#921 fix(api_utils): setup packages
  src/api_utils/setup.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#922 fix(pypi): fix checks
  .github/workflows/upload-api-utils-to-pypi.yaml
Labels: type: fix

#919 chore(docker): move docker related files to docker/ folder
  .github/workflows/gladia-base-builder.yml
  .github/workflows/gladia-builder.yml
  src/docker/.dockerignore
  src/docker/base.Dockerfile
  src/docker/docker-compose.dev.yaml
  src/docker/docker-compose.prod.yaml
  src/docker/docker-compose.yaml
  src/docker/gpu.Dockerfile
  src/howto101.md
Labels: priority: low, type: chore

#920 feat(tests): autogenerated_tests can be runned from outside
  .github/workflows/gladia-builder.yml
  src/apis/image/image/background-replacement/test_background_replacement.py
  src/apis/image/image/guided-inpainting/test_guided_inpainting.py
  src/apis/image/image/inpainting/test_inpainting.py
  src/apis/image/text/classification/test_classification.py
  src/apis/image/text/ocr/test_ocr.py
  src/apis/text/image/image-generation/test_image_generation.py
  src/apis/text/text/headline-generation/test_headline_generation.py
  src/apis/text/text/keyword-extraction/test_keyword_extraction.py
  src/apis/text/text/next-sentence-prediction/test_next_sentence_prediction.py
  src/apis/text/text/next-word-prediction/test_next_word_prediction.py
  src/apis/text/text/question-answering/test_question_answering.py
  src/apis/text/text/similarity/test_similarity.py
  src/apis/text/text/summarization/test_summarization.py
  src/apis/text/text/translation/test_translation.py
  src/apis/text/text/word-alignment/test_word-aligment.py
  src/conftest.py
  src/tester/README.md
  src/tester/__init__.py
  src/tester/constants.py
  src/tester/default_tests.py
  src/tester/test_autogenerated.py
  src/tester/utils/__init__.py
  src/tester/utils/get_data_to_test.py
Labels: type: enhancement, priority: medium, status : confirmed

#910 feat: language detection on DeepSpeed
  .github/workflows/gladia-builder.yml
  src/api_utils/gladia_api_utils/add_routes_to_router.py
  src/api_utils/gladia_api_utils/casting.py
  src/api_utils/gladia_api_utils/deepspeed_helper/__init__.py
  src/api_utils/gladia_api_utils/deepspeed_helper/warm_up.py
  src/api_utils/gladia_api_utils/submodules.py
  src/api_utils/gladia_api_utils/warm_up_in_custom_env.py
  src/api_utils/setup.py
  src/apis/image/image/super-resolution/latent-sr/latent-sr.py
  src/apis/text/text/language-detection/papluca_xlm-roberta-base-language-detection_deepspeed/env.yaml
  src/apis/text/text/language-detection/papluca_xlm-roberta-base-language-detection_deepspeed/papluca_xlm-roberta-base-language-detection_deepspeed.py
  src/apis/text/text/language-detection/task.yaml
Labels: type: enhancement, priority: medium, status : confirmed, ci: force-build-gladia

#923 fix(__init__): add missing init
  src/apis/text/text/language-detection/papluca_xlm-roberta-base-language-detection_deepspeed/__init__.py
Labels: priority: critical, type: fix

#926 ci: cd rework
  .github/workflows/deploy-completion.yml
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci

#925 feat(taskrouter): lazy warm up
  src/api_utils/gladia_api_utils/add_routes_to_router.py
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: enhancement, priority: medium, status : confirmed, auto-deploy

#911 refactor(NER): switch to DS
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english/dbmdz-bert-large-cased-finetuned-conll03-english.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/.model_metadata.yaml
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/__init__.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/env.yaml
  src/apis/text/text/named-entity-recognition/task.yaml
Labels: priority: medium, status : confirmed, type: refactor, ci: ready-to-merge, ci: force-build-gladia
