Repository gladiaio/gladia, pull requests merged in 2022-12, with the labels that each got.

#933 fix(language-detection): consistency in language detection
  src/apis/text/text/language-detection/papluca_xlm-roberta-base-language-detection_deepspeed/papluca_xlm-roberta-base-language-detection_deepspeed.py
  src/apis/text/text/language-detection/toftrup-etal-2021/env.yaml
  src/apis/text/text/language-detection/toftrup-etal-2021/toftrup-etal-2021.py
  src/docker/gpu.Dockerfile
Labels: type: fix, ci: ready-to-merge

#936 refactor(tester): move to api_utils
  .github/workflows/gladia-builder.yml
  src/api_utils/gladia_api_utils/tester/README.md
  src/api_utils/gladia_api_utils/tester/__init__.py
  src/api_utils/gladia_api_utils/tester/__main__.py
  src/api_utils/gladia_api_utils/tester/constants.py
  src/api_utils/gladia_api_utils/tester/default_tests.py
  src/api_utils/gladia_api_utils/tester/test_autogenerated.py
  src/api_utils/gladia_api_utils/tester/utils/__init__.py
  src/api_utils/gladia_api_utils/tester/utils/get_data_to_test.py
  src/api_utils/setup.py
  src/apis/image/image/background-replacement/test_background_replacement.py
  src/apis/image/image/guided-inpainting/test_guided_inpainting.py
  src/apis/image/image/inpainting/test_inpainting.py
  src/apis/image/text/classification/test_classification.py
  src/apis/image/text/ocr/test_ocr.py
  src/apis/text/image/image-generation/test_image_generation.py
  src/apis/text/text/headline-generation/test_headline_generation.py
  src/apis/text/text/keyword-extraction/test_keyword_extraction.py
  src/apis/text/text/next-sentence-prediction/test_next_sentence_prediction.py
  src/apis/text/text/next-word-prediction/test_next_word_prediction.py
  src/apis/text/text/question-answering/test_question_answering.py
  src/apis/text/text/similarity/test_similarity.py
  src/apis/text/text/summarization/test_summarization.py
  src/apis/text/text/translation/test_translation.py
  src/apis/text/text/word-alignment/test_word-aligment.py
Labels: priority: high, status : confirmed, type: refactor

#938 fix(upload-api-utils-to-pypi.yaml): fix the pypi build + upload
  .github/workflows/upload-api-utils-to-pypi.yaml
Labels: type: fix, ci: ready-to-merge

#940 refactor(create_custom_envs): fix smells in create_custom_envs
  src/tools/venv-builder/create_custom_envs.py
Labels: type: refactor, ci: ready-to-merge

#941 fix: tester is imported from api_utils
  src/api_utils/gladia_api_utils/tester/test_autogenerated.py
  src/apis/image/image/background-replacement/test_background_replacement.py
  src/apis/image/image/guided-inpainting/test_guided_inpainting.py
  src/apis/image/image/inpainting/test_inpainting.py
  src/apis/image/text/classification/test_classification.py
  src/apis/image/text/ocr/test_ocr.py
  src/apis/text/image/image-generation/test_image_generation.py
  src/apis/text/text/headline-generation/test_headline_generation.py
  src/apis/text/text/keyword-extraction/test_keyword_extraction.py
  src/apis/text/text/next-sentence-prediction/test_next_sentence_prediction.py
  src/apis/text/text/next-word-prediction/test_next_word_prediction.py
  src/apis/text/text/question-answering/test_question_answering.py
  src/apis/text/text/similarity/test_similarity.py
  src/apis/text/text/summarization/test_summarization.py
  src/apis/text/text/translation/test_translation.py
  src/apis/text/text/word-alignment/test_word-aligment.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#924 feat(MII_MODEL_PATH): handle cache for mii
  src/docker/gpu.Dockerfile
  src/run_server.sh
Labels: type: enhancement, priority: medium, status : confirmed, ci: ready-to-merge, auto-deploy

#939 feat(language-codes): add language-codes references
  src/apis/text/text/language-codes/__init__.py
  src/apis/text/text/language-codes/language-codes/__init__.py
  src/apis/text/text/language-codes/language-codes/env.yaml
  src/apis/text/text/language-codes/language-codes/language-codes.py
  src/apis/text/text/language-codes/task.yaml
Labels: type: enhancement, ci: ready-to-merge, ci: force-build-gladia, ci: build-base

#945 fix(compvis.py): fix upgrade diffuser
  src/apis/image/image/guided-inpainting/compvis/compvis.py
Labels: type: fix, ci: ready-to-merge

#950 fix(gpu.Docker): fix jax-preallocation
  src/docker/gpu.Dockerfile
Labels: type: fix, ci: ready-to-merge, auto-deploy

#949 feat(spacy-en-ner): add spacy for ner as default
  src/apis/text/text/named-entity-recognition/spacy-en/.model_metadata.yaml
  src/apis/text/text/named-entity-recognition/spacy-en/__init__.py
  src/apis/text/text/named-entity-recognition/spacy-en/spacy-en.py
  src/apis/text/text/named-entity-recognition/task.yaml
  src/run_server.sh
  src/warm_up.py
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#946 feat(runwayml): add runwayml as default for image generation
  src/apis/text/image/image-generation/compvis-sd-14/.model_metadata.yaml
  src/apis/text/image/image-generation/compvis-sd-14/__init__.py
  src/apis/text/image/image-generation/compvis-sd-14/compvis-sd-14.py
  src/apis/text/image/image-generation/compvis-sd-14/unsafe.png
  src/apis/text/image/image-generation/runwayml-sd-15/.model_metadata.yaml
  src/apis/text/image/image-generation/runwayml-sd-15/__init__.py
  src/apis/text/image/image-generation/runwayml-sd-15/runwayml-sd-15.py
  src/apis/text/image/image-generation/runwayml-sd-15/unsafe.png
  src/apis/text/image/image-generation/task.yaml
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#948 fix(language-detection): switch model to avoid cublas OOM
  src/apis/text/text/language-detection/task.yaml
Labels: type: fix, ci: ready-to-merge, auto-deploy

#951 feat(model_versioning): add capability to handle model versioning inside a model_type
  src/api_utils/gladia_api_utils/add_routes_to_router.py
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/audio/text/audio-transcription/coqui_english_huge_vocab/coqui_english_huge_vocab.py
  src/apis/audio/text/audio-transcription/openai-whisper-base/openai-whisper-base.py
  src/apis/audio/text/audio-transcription/openai-whisper-large/.model_metadata.yaml
  src/apis/audio/text/audio-transcription/openai-whisper-large/__init__.py
  src/apis/audio/text/audio-transcription/openai-whisper-medium/.model_metadata.yaml
  src/apis/audio/text/audio-transcription/openai-whisper-medium/__init__.py
  src/apis/audio/text/audio-transcription/openai-whisper-medium/openai-whisper-medium.py
  src/apis/audio/text/audio-transcription/openai-whisper-small/.model_metadata.yaml
  src/apis/audio/text/audio-transcription/openai-whisper-small/__init__.py
  src/apis/audio/text/audio-transcription/openai-whisper-small/openai-whisper-small.py
  src/apis/audio/text/audio-transcription/openai-whisper-tiny/.model_metadata.yaml
  src/apis/audio/text/audio-transcription/openai-whisper-tiny/__init__.py
  src/apis/audio/text/audio-transcription/openai-whisper-tiny/openai-whisper-tiny.py
  src/apis/audio/text/audio-transcription/openai-whisper/.model_metadata.yaml
  src/apis/audio/text/audio-transcription/openai-whisper/__init__.py
  src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
  src/apis/audio/text/audio-transcription/task.yaml
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#952 feat(multichannel-transcription): add multichannel-transcription
  src/apis/audio/text/audio-transcription/openai-whisper/.model_metadata.yaml
  src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
  src/env.yaml
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#954 fix(953-punctuation): fix punctuation for multiple sentences
  src/apis/text/text/punctuation-restoration/kredor-punctuate-all/kredor-punctuate-all.py
Labels: type: fix, ci: ready-to-merge, auto-deploy

#955 feat(whisper): add large-v1 and large-v2
  src/apis/audio/text/audio-transcription/openai-whisper/.model_metadata.yaml
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#956 feat(sd2): add sd2
  src/apis/text/image/image-generation/runwayml-sd-15/.model_metadata.yaml
  src/apis/text/image/image-generation/runwayml-sd-15/__init__.py
  src/apis/text/image/image-generation/runwayml-sd-15/runwayml-sd-15.py
  src/apis/text/image/image-generation/runwayml-sd-15/unsafe.png
  src/apis/text/image/image-generation/stable-diffusion/.model_metadata.yaml
  src/apis/text/image/image-generation/stable-diffusion/__init__.py
  src/apis/text/image/image-generation/stable-diffusion/stable-diffusion.py
  src/apis/text/image/image-generation/stable-diffusion/unsafe.png
  src/apis/text/image/image-generation/task.yaml
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#958 docs(README.md): readme
  README.md
Labels: type: documentation

#960 fix(guided-inpainting): typo
  src/apis/image/image/guided-inpainting/task.yaml
Labels: type: fix, ci: ready-to-merge, ci: force-build-gladia, auto-deploy

#961 feat(image-guided-inpainting): add image-guided-inpainting
  src/apis/image/image/image-guided-inpainting/__init__.py
  src/apis/image/image/image-guided-inpainting/fantasy-studio/__init__.py
  src/apis/image/image/image-guided-inpainting/fantasy-studio/fantasy-studio.py
  src/apis/image/image/image-guided-inpainting/image-guided-inpainting.py
  src/apis/image/image/image-guided-inpainting/task.yaml
Labels: type: enhancement, ci: ready-to-merge, ci: force-build-gladia, auto-deploy

#962 test: vram usage
  src/api_utils/gladia_api_utils/tester/default_tests.py
  src/api_utils/setup.py
  src/env.yaml
Labels: ci: ready-to-merge, type: test

#964 feat(image-generation): v2.1
  src/apis/text/image/image-generation/stable-diffusion/.model_metadata.yaml
  src/apis/text/image/image-generation/stable-diffusion/stable-diffusion.py
  src/apis/text/image/image-generation/task.yaml
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#966 fix(stable-diffusion): move to sd21-base
  src/apis/text/image/image-generation/stable-diffusion/stable-diffusion.py
  src/apis/text/image/image-generation/task.yaml
Labels: type: fix, ci: ready-to-merge, auto-deploy

#971 ci(notification): remove
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-completion.yml
  .github/workflows/gladia-base-builder.yml
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-latest-deploy.yml
  .github/workflows/pr-linter.yml
  .github/workflows/upload-api-utils-to-pypi.yaml
Labels: type: ci

#969 fix(submodules): fix 968 handle 0 int as valid input
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: fix, ci: ready-to-merge, auto-deploy

#970 fix(stable-diffusion): add random seed int 0
  src/apis/text/image/image-generation/stable-diffusion/stable-diffusion.py
Labels: type: fix, ci: ready-to-merge, auto-deploy

#967 fix(image-generation): set random seed when 0
  src/apis/text/image/image-generation/stable-diffusion/stable-diffusion.py
Labels: type: fix, ci: ready-to-merge, auto-deploy

#972 fix(submodule): remove unwanted debug logs
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: fix, ci: ready-to-merge, auto-deploy

#974 docs(tasks): doc for 0 random seed
  src/apis/text/image/image-generation/task.yaml
Labels: type: documentation, ci: ready-to-merge, auto-deploy

#975 docs(test): better test doc
  src/api_utils/gladia_api_utils/tester/README.md
Labels: type: documentation, ci: ready-to-merge, auto-deploy

#977 refactor(uncolorization): easier uncolorization
  src/apis/image/image/uncolorization/v1/v1.py
Labels: type: refactor, ci: ready-to-merge, auto-deploy

#976 feat(image-guided-inpatining): better default guidance
  src/apis/image/image/image-guided-inpainting/fantasy-studio/fantasy-studio.py
  src/apis/image/image/image-guided-inpainting/task.yaml
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#979 feat(submodules): retrieve logs from subprocesses
  src/api_utils/gladia_api_utils/submodules.py
Labels: type: enhancement, ci: ready-to-merge, auto-deploy

#980 refactor: rename warm_up to prepare
  src/api_utils/gladia_api_utils/add_routes_to_router.py
  src/api_utils/gladia_api_utils/deepspeed_helper/__init__.py
  src/api_utils/gladia_api_utils/deepspeed_helper/prepare.py
  src/api_utils/gladia_api_utils/prepare_in_custom_env.py
  src/api_utils/gladia_api_utils/submodules.py
  src/api_utils/setup.py
  src/apis/text/text/language-detection/papluca_xlm-roberta-base-language-detection_deepspeed/papluca_xlm-roberta-base-language-detection_deepspeed.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed.py
  src/prepare.py
  src/run_server.sh
Labels: type: refactor, ci: ready-to-merge

#981 feat(env.yaml): notify
  .github/workflows/deploy-completion.yml
  .github/workflows/notify.yml
Labels: type: enhancement, ci: ready-to-merge

#984 fix: bad name of label in ci and remove labeler for non existant l…
  .github/labeler.yml
  .github/workflows/gladia-builder.yml
Labels: type: ci

#987 fix(text-summarization): fix prediction
  src/apis/text/text/conversation-summarization/bart-large-xsum-samsum/bart-large-xsum-samsum.py
Labels: type: fix, ci: ready-to-merge

#989 refactor(prepare): optimize prepare
  src/prepare.py
Labels: type: refactor, ci: ready-to-merge

#973 feat(video-classification-kinetics): add video-classification
  src/apis/video/text/__init__.py
  src/apis/video/text/action-classifications/__init__.py
  src/apis/video/text/action-classifications/kinetics/.model_metadata.yaml
  src/apis/video/text/action-classifications/kinetics/__init__.py
  src/apis/video/text/action-classifications/kinetics/env.yaml
  src/apis/video/text/action-classifications/kinetics/kinetics.py
  src/apis/video/text/action-classifications/task.yaml
  src/env.yaml
  src/tools/venv-builder/envs/video/base.yaml
Labels: type: enhancement, ci: ready-to-merge

#995 fix(run_server): fix torch cache location
  src/run_server.sh
Labels: type: fix, ci: ready-to-merge

#992 feat(punctuation-restoration): better punctuation-restoration
  src/api_utils/gladia_api_utils/model_management.py
  src/api_utils/gladia_api_utils/nlp.py
  src/api_utils/gladia_api_utils/system.py
  src/apis/text/text/language-detection/toftrup-etal-2021/env.yaml
  src/apis/text/text/named-entity-recognition/spacy-en/.model_metadata.yaml
  src/apis/text/text/named-entity-recognition/spacy-multilingual/.model_metadata.yaml
  src/apis/text/text/named-entity-recognition/spacy-multilingual/__init__.py
  src/apis/text/text/named-entity-recognition/spacy-multilingual/spacy-multilingual.py
  src/apis/text/text/named-entity-recognition/task.yaml
  src/apis/text/text/punctuation-restoration/notaitech-fastpunct/.model_metadata.yaml
  src/apis/text/text/punctuation-restoration/notaitech-fastpunct/notaitech-fastpunct.py
  src/apis/text/text/punctuation-restoration/oguhr-multilingualpunctuation/.model_metadata.yaml
  src/apis/text/text/punctuation-restoration/oguhr-multilingualpunctuation/__init__.py
  src/apis/text/text/punctuation-restoration/oguhr-multilingualpunctuation/oguhr-multilingualpunctuation.py
  src/apis/text/text/punctuation-restoration/task.yaml
  src/config.json
  src/env.yaml
  src/prepare.py
Labels: type: enhancement, ci: ready-to-merge

#997 fix(prepare): fix en_core_web_lg reference
  src/prepare.py
Labels: priority: critical, type: fix, ci: ready-to-merge

#998 fix(speaker-diarization): return if pipeline loading fails
  src/apis/audio/text/speaker-diarization/pyannote-speaker_diarization/pyannote-speaker_diarization.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#1001 ci: EoL previous infra + fix notify (v2)
  .github/workflows/deploy-completion.yml
  .github/workflows/gladia-latest-deploy.yml
  README.md
Labels: type: ci, ci: ready-to-merge, ci: force-build-gladia

#999 fix(openai-whisper): strip sentence
  src/README.md
  src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
Labels: type: fix, ci: ready-to-merge, ci: force-build-gladia, ci: force-build-base, ci: build-base

#1005 perf(prepare): multithread the prepare.py
  src/prepare.py
Labels: ci: ready-to-merge, type: performance

#1002 refactor(conf): split system conf and models conf
  src/api_utils/gladia_api_utils/model_management.py
  src/api_utils/gladia_api_utils/system.py
  src/config.json
  src/models-config.json
  src/prepare.py
Labels: type: refactor, ci: ready-to-merge

#1006 feat(image-generation-prompt-beautifier): add image-generation-prompt…
  src/apis/text/text/image-generation-prompt-beautifier/__init__.py
  src/apis/text/text/image-generation-prompt-beautifier/ms-promptist/__init__.py
  src/apis/text/text/image-generation-prompt-beautifier/ms-promptist/ms-promptist.py
  src/apis/text/text/image-generation-prompt-beautifier/task.yaml
Labels: type: enhancement, ci: ready-to-merge

#1007 fix(conversation-summarization): use the map reduce algo when it's needed
  src/apis/text/text/conversation-summarization/bart-large-xsum-samsum/bart-large-xsum-samsum.py
Labels: priority: critical, type: fix

#1008 fix(address-formatting): implement a rate limiter
  src/apis/text/text/address-formatting/geopy-formatter/geopy-formatter.py
Labels: type: fix, ci: ready-to-merge

#1009 fix(address-formatting): return correct message when address not found
  src/apis/text/text/address-formatting/geopy-formatter/geopy-formatter.py
Labels: type: fix, ci: ready-to-merge

#1014 fix(conversation-summarization): use Bart tokenizer to have the correct number of real chunks
  src/apis/text/text/conversation-summarization/bart-large-xsum-samsum/bart-large-xsum-samsum.py
Labels: priority: high, type: fix

#1016 feat(submodules): add types Array for the swagger UI
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/image/image/background-replacement/task.yaml
Labels: priority: high

#1020 feat(diarization): add diarization guidance
  src/apis/audio/text/audio-transcription/coqui_english_huge_vocab/coqui_english_huge_vocab.py
  src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
  src/apis/audio/text/audio-transcription/task.yaml
  src/apis/audio/text/speaker-diarization/pyannote-speaker_diarization/pyannote-speaker_diarization.py
  src/apis/audio/text/speaker-diarization/task.yaml
Labels: type: enhancement
