Repository gladiaio/gladia, pull requests merged in 2022-09, with the labels that each got.

#694 fix(colorization): add better example file
  src/apis/image/image/colorization.py
Labels: type: fix, ci: ready-to-merge

#695 fix(face-bluring): adapt face-bluring example
  src/apis/image/image/face-bluring.py
Labels: type: fix, ci: ready-to-merge

#696 fix(uncolorization): change default example
  src/apis/image/image/uncolorization.py
Labels: type: fix, ci: ready-to-merge

#705 fix(colorization): move RGBA to RGB
  src/apis/image/image/colorization-models/deoldify-artistic/deoldify-artistic.py
  src/apis/image/image/colorization-models/deoldify-stable/deoldify-stable.py
Labels: type: fix, ci: ready-to-merge

#701 perf(background-removal): switch background removal mobilenet model to onnx format
  src/api_utils/gladia_api_utils/model_management.py
  src/apis/image/image/background-removal-models/mobilenet/env.yaml
  src/apis/image/image/background-removal-models/mobilenet/mobilenet.py
  src/apis/image/image/background-removal.py
  src/env.yaml
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: performance

#711 refactor(ocr): change default model to tesseract-denoising
  src/apis/image/text/ocr.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge

#713 feat(language-generation): bloom-560m
  src/apis/text/text/language-generation-models/bloom-560m/bloom-560m.py
  src/apis/text/text/language-generation.py
  src/main.py
Labels: type: enhancement, type: new model, priority: high, status : confirmed, ci: ready-to-merge

#712 ci(slack): add slack notifications
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#716 fix(init): add init to bloom
  src/apis/text/text/language-generation-models/bloom-560m/__init__.py
Labels: priority: high, type: fix, ci: ready-to-merge

#719 feat(api): add top_k inputs and switch default model of question answering
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-MiniLM-L6-v2/keybert-paraphrase-MiniLM-L6-v2.py
  src/apis/text/text/keyword-extraction-models/keybert-paraphrase-multilingual-MiniLM-L12-v2/keybert-paraphrase-multilingual-MiniLM-L12-v2.py
  src/apis/text/text/keyword-extraction.py
  src/apis/text/text/next-word-prediction-models/albert-base-v2/albert-base-v2.py
  src/apis/text/text/next-word-prediction-models/bert-base-uncased/bert-base-uncased.py
  src/apis/text/text/next-word-prediction-models/distilbert-base-uncased/distilbert-base-uncased.py
  src/apis/text/text/next-word-prediction-models/roberta-base/roberta-base.py
  src/apis/text/text/next-word-prediction.py
  src/apis/text/text/question-answering-models/deepset-roberta-base-squad2/deepset-roberta-base-squad2.py
  src/apis/text/text/question-answering-models/deepset_bert-base-cased-squad2/deepset_bert-base-cased-squad2.py
  src/apis/text/text/question-answering-models/distilbert-base-cased-distilled-squad/distilbert-base-cased-distilled-squad.py
  src/apis/text/text/question-answering-models/mfeb-albert-xxlarge-v2-squad2/mfeb-albert-xxlarge-v2-squad2.py
  src/apis/text/text/question-answering-models/mrm8488-bert-tiny-5-finetuned-squadv2/mrm8488-bert-tiny-5-finetuned-squadv2.py
  src/apis/text/text/question-answering.py
Labels: type: enhancement, ci: ready-to-merge

#710 feat(test/api): add specific inputs for task examples and test
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/audio/text/audio-transcription.py
  src/apis/image/image/background-removal.py
  src/apis/image/image/colorization.py
  src/apis/image/image/face-bluring.py
  src/apis/image/image/uncolorization.py
  src/apis/image/text/asciify.py
  src/apis/image/text/classification.py
  src/apis/image/text/ocr-models/tesseract-default/tesseract-default.py
  src/apis/image/text/ocr-models/tesseract-denoising/tesseract-denoising.py
  src/apis/image/text/ocr.py
  src/env.yaml
  src/unit-test/test.py
Labels: type: enhancement, ci: ready-to-merge

#721 fix(train): rework to make ci compatible with merge trains
  .github/workflows/gladia-base-builder.yml
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-latest-deploy.yml
  src/gpu.Dockerfile
Labels: type: fix

#722 fix(super-resolution): fix wrong default model
  src/apis/image/image/super-resolution.py
Labels: type: fix, ci: ready-to-merge

#726 ci(gladia-builder): building image only when necessary
  .github/workflows/gladia-builder.yml
  src/apis/image/image/super-resolution-models/latent-sr/latent-sr.py
  src/apis/image/image/super-resolution-models/latent-sr/ldm/models/autoencoder.py
  src/apis/image/image/super-resolution-models/latent-sr/ldm/models/diffusion/classifier.py
  src/apis/image/image/super-resolution-models/latent-sr/ldm/models/diffusion/ddim.py
  src/apis/image/image/super-resolution-models/latent-sr/ldm/models/diffusion/ddpm.py
  src/apis/image/image/super-resolution-models/latent-sr/ldm/models/diffusion/plms.py
Labels: type: ci

#724 ci(builder-main): add timeout-minutes: 90 for main
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#725 fix(super-resolution): fix missing package
  src/apis/image/image/super-resolution-models/latent-sr/env.yaml
Labels: type: fix, ci: ready-to-merge

#715 refactor(bloom): docstring format
  src/apis/text/text/language-generation-models/bloom-560m/bloom-560m.py
Labels: priority: low, type: refactor, ci: ready-to-merge

#702 perf(background-removal): switch background removal exception model to onnx format
  src/apis/image/image/background-removal-models/xception/env.yaml
  src/apis/image/image/background-removal-models/xception/xception.py
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: performance

#728 fix(builder): remove mounted artifacts at tear down
  .github/workflows/gladia-builder.yml
Labels: type: fix

#709 fix(ocr): check ocr language
  src/apis/image/text/ocr-models/easy-ocr/easy-ocr.py
  src/apis/image/text/ocr.py
Labels: type: fix, ci: ready-to-merge

#698 fix(ocr): fix bad outputs
  src/apis/image/text/ocr-models/tesseract-default/tesseract-default.py
  src/apis/image/text/ocr-models/tesseract-denoising/tesseract-denoising.py
Labels: type: fix, ci: ready-to-merge

#727 fix(gpu.Dockerfile): missing TRITON_MODELS_PATH
  src/gpu.Dockerfile
Labels: type: fix

#729 fix(face-bluring): coordinates are now correctly fetched
  src/apis/image/image/face-bluring-models/ageitgey/ageitgey.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#730 feat(hate-speech): byt5-base-tweet-hate-detection
  src/apis/text/text/hate-speech-detection-models/byt5-base-tweet-hate-detection/__init__.py
  src/apis/text/text/hate-speech-detection-models/byt5-base-tweet-hate-detection/byt5-base-tweet-hate-detection.py
  src/apis/text/text/hate-speech-detection.py
  src/config.json
Labels: type: enhancement, type: new model, priority: medium, status : confirmed, ci: ready-to-merge

#707 refactor(main): refactor the main scripts for docstring
  src/main.py
  src/tools/ci/run_ci_pr.py
  src/warm_up.py
Labels: type: refactor, ci: ready-to-merge

#734 ci(buidler): set debug lvl
  .github/workflows/gladia-builder.yml
Labels: type: ci, ci: ready-to-merge

#740 refactor(super-resolution): clean code
  src/apis/image/image/super-resolution-models/latent-sr/ldm/models/diffusion/ddpm.py
  src/apis/image/image/super-resolution-models/latent-sr/ldm/modules/diffusionmodules/model.py
  src/apis/image/image/super-resolution-models/latent-sr/notebook_helpers.py
Labels: type: refactor, ci: ready-to-merge

#703 refactor(api_utils): move to docstring
  src/api_utils/gladia_api_utils/CoquiEngineHelper.py
  src/api_utils/gladia_api_utils/TorchvisionModelHelper.py
  src/api_utils/gladia_api_utils/casting.py
  src/api_utils/gladia_api_utils/file_management.py
  src/api_utils/gladia_api_utils/get_activated_task_path.py
  src/api_utils/gladia_api_utils/image_management.py
  src/api_utils/gladia_api_utils/io.py
  src/api_utils/gladia_api_utils/metadata.py
  src/api_utils/gladia_api_utils/model_management.py
  src/api_utils/gladia_api_utils/responses.py
  src/api_utils/gladia_api_utils/run_process.py
  src/api_utils/gladia_api_utils/secret_management.py
  src/api_utils/gladia_api_utils/submodules.py
  src/api_utils/gladia_api_utils/system.py
  src/api_utils/gladia_api_utils/triton_helper/data_processing.py
  src/api_utils/gladia_api_utils/triton_helper/download_active_models.py
  src/api_utils/gladia_api_utils/triton_helper/helper.py
  src/base.Dockerfile
  src/gpu.Dockerfile
Labels: type: refactor, ci: ready-to-merge

#736 feat(deblurring): add deblurring task
  src/apis/image/image/deblurring-models/CMFNet/CMFNet.py
  src/apis/image/image/deblurring-models/CMFNet/__init__.py
  src/apis/image/image/deblurring-models/CMFNet/model/CMFNet.py
  src/apis/image/image/deblurring-models/CMFNet/model/__init__.py
  src/apis/image/image/deblurring-models/CMFNet/model/block.py
  src/apis/image/image/deblurring-models/__init__.py
  src/apis/image/image/deblurring.py
  src/env.yaml
  src/main.py
Labels: type: enhancement, ci: ready-to-merge, ci: force-build-gladia

#743 ci(deploy): change main file changes trigger
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#742 ci(gladia-builder): fix changed file trigger
  .github/workflows/gladia-builder.yml
Labels: type: ci, ci: ready-to-merge

#746 ci(deploy): fix diff detection
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge, ci: force-build-gladia

#749 refactor(smell): fix code smells
  .github/workflows/gladia-builder.yml
  src/api_utils/gladia_api_utils/CoquiEngineHelper.py
  src/api_utils/gladia_api_utils/OVHFileManager.py
  src/api_utils/gladia_api_utils/casting.py
  src/api_utils/gladia_api_utils/file_management.py
  src/api_utils/gladia_api_utils/get_activated_task_path.py
  src/api_utils/gladia_api_utils/image_management.py
  src/api_utils/gladia_api_utils/metadata.py
  src/api_utils/gladia_api_utils/model_management.py
  src/api_utils/gladia_api_utils/secret_management.py
  src/api_utils/gladia_api_utils/submodules.py
  src/api_utils/gladia_api_utils/system.py
  src/api_utils/gladia_api_utils/triton_helper/download_active_models.py
  src/api_utils/gladia_api_utils/triton_helper/helper.py
  src/apis/image/image/background-removal-models/mobilenet/mobilenet.py
  src/apis/image/image/background-removal-models/xception/xception.py
  src/apis/image/image/colorization-models/deoldify-artistic/deoldify-artistic.py
  src/apis/image/image/colorization-models/deoldify-stable/deoldify-stable.py
  src/apis/image/image/deblurring-models/CMFNet/CMFNet.py
  src/apis/image/image/face-bluring-models/ageitgey/ageitgey.py
  src/apis/image/image/uncolorization-models/v1/v1.py
  src/apis/text/image/image-generation-models/dream-studio/dream-studio.py
  src/apis/text/text/programming-language-generation-models/sentdex-GPyT/sentdex-GPyT.py
  src/base.Dockerfile
  src/gpu.Dockerfile
  src/unit-test/test.py
Labels: type: refactor, ci: ready-to-merge, ci: test-continue-when-fail, ci: force-test-all-models, ci: force-build-gladia

#747 feat(colorization): mlhubber colorize model
  src/apis/image/image/colorization-models/mlhubber_colorize/.model_metadata.yaml
  src/apis/image/image/colorization-models/mlhubber_colorize/__init__.py
  src/apis/image/image/colorization-models/mlhubber_colorize/mlhubber_colorize.py
  src/apis/image/image/colorization.py
  src/apis/image/image/super-resolution-models/latent-sr/latent-sr.py
Labels: type: enhancement, type: new model, priority: medium, status : confirmed, ci: ready-to-merge, ci: force-build-gladia

#751 ci(rework): full promote rework, improved build
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge, ci: force-build-gladia, ci: force-build-base, ci: build-base

#757 ci(noise): naming workflow correctly and test
  .github/workflows/gladia-builder.yml
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#758 feat(inpainting): add inpainting
  src/apis/image/image/inpainting-models/stable-diffusion/__init__.py
  src/apis/image/image/inpainting-models/stable-diffusion/stable-diffusion.py
  src/apis/image/image/inpainting.py
  src/env.yaml
Labels: type: enhancement

#760 test(test.py): assert output type to true
  src/unit-test/test.py
Labels: type: test

#761 fix(OVHFileManager): fix logger
  src/api_utils/gladia_api_utils/OVHFileManager.py
Labels: type: fix

#767 fix(inpainting): clean old artifacts
  src/apis/image/image/guided-inpainting-models/co-mod-gan/.model_metadata.yaml
  src/apis/image/image/guided-inpainting-models/co-mod-gan/__init__.py
  src/apis/image/image/guided-inpainting-models/co-mod-gan/co-mod-gan.py
  src/apis/image/image/guided-inpainting-models/hypergraphs/.model_metadata.yaml
  src/apis/image/image/guided-inpainting-models/hypergraphs/__init__.py
  src/apis/image/image/guided-inpainting-models/hypergraphs/hypergraphs.py
Labels: type: fix, ci: ready-to-merge

#764 refactor(dosctring): add docstring to Fourier Inpainting
  src/api_utils/gladia_api_utils/inpainting_helper/model/fcf.py
  src/api_utils/gladia_api_utils/inpainting_helper/model/mat.py
Labels: type: refactor, ci: ready-to-merge

#750 feat(api): add missing models outputs and fix missing metadata file error
  src/api_utils/gladia_api_utils/metadata.py
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/image/image/background-removal.py
  src/apis/text/text/hate-speech-detection-models/byt5-base-tweet-hate-detection/.model_metadata.yaml
  src/apis/text/text/sentence-paraphraser-models/ramsrigouthamg-t5-large-paraphraser-diverse-high-quality/.model_metadata.yaml
  src/apis/text/text/sentence-paraphraser-models/ramsrigouthamg-t5_sentence_paraphraser/.model_metadata.yaml
  src/apis/text/text/summarization-models/all-MiniLM-L6-v2/.model_metadata.yaml
  src/unit-test/test.py
Labels: type: bug, type: enhancement, priority: low, ci: ready-to-merge, ci: force-no-cache

#765 feat: Base for FT & background removal FTs
  src/apis/image/image/IBasicTestsImageToImage.py
  src/apis/image/image/background-removal-models/test_background_removal.py
  src/env.yaml
  src/pytest.ini
  src/tests/__init__.py
  src/tests/constants.py
  src/tests/utils/__init__.py
  src/tests/utils/get_models_to_test.py
Labels: type: enhancement, help wanted, priority: medium, status : confirmed, ci: ready-to-merge, ci: force-no-cache, ci: force-build-gladia, ci: build-base

#768 feat(headline): add headline generation
  src/apis/text/text/headline-generation-models/__init__.py
  src/apis/text/text/headline-generation-models/michau-t5-base-en-generate-headline/__init__.py
  src/apis/text/text/headline-generation-models/michau-t5-base-en-generate-headline/michau-t5-base-en-generate-headline.py
  src/apis/text/text/headline-generation.py
Labels: type: enhancement, ci: ready-to-merge

#770 refactor(sentence-paraphraser): change default model
  src/apis/text/text/sentence-paraphraser.py
Labels: type: refactor, ci: ready-to-merge

#771 refactor(env.yaml): move pytest to conda-forge
  src/env.yaml
Labels: type: refactor, ci: ready-to-merge

#766 refactor(bg_removal): add wrapping class to fix code deduplication + gain perf x2
  src/apis/image/image/background-removal-models/OnnxBackgroundRemoval.py
  src/apis/image/image/background-removal-models/mobilenet/mobilenet.py
  src/apis/image/image/background-removal-models/xception/xception.py
Labels: type: refactor, ci: ready-to-merge

#772 feat(test): default models only cmd arg
  src/conftest.py
  src/tests/utils/get_models_to_test.py
Labels: type: enhancement, priority: medium, status : confirmed, ci: ready-to-merge

#775 feat(test): generate tests based on input examples
  src/apis/image/image/IBasicTestsImageToImage.py
  src/apis/image/image/background-removal-models/test_background_removal.py
  src/conftest.py
  src/tests/utils/__init__.py
  src/tests/utils/get_data_to_test.py
  src/tests/utils/get_models_to_test.py
Labels: type: enhancement, priority: high, status : confirmed, ci: ready-to-merge

#778 ci(deploy): always restart aipi
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#779 fix(global): check if env variable exist before retrieving it
  src/tests/utils/get_data_to_test.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#776 test(inpainting): basic FTs
  src/apis/image/image/inpainting-models/test_inpainting.py
  src/pytest.ini
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: test

#774 feat(image-generation): support samples > 1
  src/api_utils/gladia_api_utils/image_management.py
  src/apis/text/image/image-generation-models/dream-studio/dream-studio.py
  src/apis/text/image/image-generation-models/dream-studio/env.yaml
  src/apis/text/image/image-generation-models/stable-diffusion/env.yaml
  src/apis/text/image/image-generation-models/stable-diffusion/stable-diffusion.py
  src/env.yaml
Labels: type: enhancement, ci: ready-to-merge

#781 ci(sleep): sleep between workers deployment
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#783 refactor(plural): plural task no longer exists
  src/apis/text/text/plural-models/.task_metadata.yaml
  src/apis/text/text/plural-models/__init__.py
  src/apis/text/text/plural-models/inflect/.model_metadata.yaml
  src/apis/text/text/plural-models/inflect/__init__.py
  src/apis/text/text/plural-models/inflect/inflect.py
  src/apis/text/text/plural.py
Labels: priority: critical, status : confirmed, ci: ready-to-merge

#784 refactor(scaffold): delete scaffold-model.py
  src/env.yaml
  src/licenses-used.md
  src/scaffold-model.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge, ci: force-build-gladia

#780 test(guided-inpainting): basic FTs
  src/apis/image/image/guided-inpainting-models/test_guided_inpainting.py
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: test

#785 test(face-blurring): basic FTs
  src/apis/image/image/face-bluring-models/test_face_blurring.py
Labels: priority: high, status : confirmed, ci: ready-to-merge, type: test

#782 fix(main): __module_is_an_input_type is now called
  src/main.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge, ci: force-build-gladia

#787 test(uncolorization): basic FTs
  src/apis/image/image/uncolorization-models/.task_metadata.yaml
  src/apis/image/image/uncolorization-models/test_uncolorization.py
Labels: priority: high, status : confirmed, ci: ready-to-merge, type: test

#788 test(deblurring): basic FTs
  src/apis/image/image/deblurring-models/test_deblurring.py
Labels: priority: high, status : confirmed, ci: ready-to-merge, type: test

#789 test(colorization): basic FTs
  src/apis/image/image/colorization-models/test_colorization.py
Labels: priority: high, status : confirmed, ci: ready-to-merge, type: test

#790 ci(build): remove secret dependencies
  .github/workflows/gladia-builder.yml
Labels: priority: critical, type: ci, ci: ready-to-merge

#786 test(super-resolution): basic FTs
  src/apis/image/image/super-resolution-models/test_super_resolution.py
Labels: priority: high, status : confirmed, ci: ready-to-merge, type: test

#791 fix(submodule): worker no longer crash when local task fail
  src/api_utils/gladia_api_utils/submodules.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#792 ci(deploy): remove secrets
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci

#793 test: create default image to image tests
  src/apis/image/image/IBasicTestsImageToImage.py
  src/apis/image/image/background-removal-models/.task_metadata.yaml
  src/apis/image/image/background-removal-models/test_background_removal.py
  src/apis/image/image/colorization-models/test_colorization.py
  src/apis/image/image/deblurring-models/test_deblurring.py
  src/apis/image/image/face-bluring-models/test_face_blurring.py
  src/apis/image/image/guided-inpainting-models/test_guided_inpainting.py
  src/apis/image/image/inpainting-models/test_inpainting.py
  src/apis/image/image/super-resolution-models/test_super_resolution.py
  src/apis/image/image/uncolorization-models/test_uncolorization.py
  src/tests/__init__.py
  src/tests/default_image_to_image_tests.py
  src/tests/utils/get_data_to_test.py
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: test

#796 test(image-generation): basic FTs
  src/apis/text/image/image-generation-models/.task_metadata.yaml
  src/apis/text/image/image-generation-models/test_image_generation.py
  src/apis/text/image/image-generation.py
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: test

#797 ci(notif): fix webhook
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#795 test: image to text FTs
  src/apis/image/text/asciify-models/.task_metadata.yaml
  src/apis/image/text/asciify-models/test_asciify.py
  src/apis/image/text/classification-models/.task_metadata.yaml
  src/apis/image/text/classification-models/test_classification.py
  src/apis/image/text/ocr-models/.task_metadata.yaml
  src/apis/image/text/ocr-models/test_ocr.py
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: test

#799 refactor(tasks): use task_metadata to retrieve example value
  src/apis/audio/text/audio-transcription-models/.task_metadata.yaml
  src/apis/audio/text/audio-transcription.py
  src/apis/image/text/asciify.py
  src/apis/image/text/classification.py
  src/apis/image/text/ocr.py
  src/apis/video/video/frame-interpolation-models/.task_metadata.yaml
  src/apis/video/video/frame-interpolation.py
Labels: priority: low, status : confirmed, type: refactor, ci: ready-to-merge

#804 fix(run_process): remove useless print
  src/api_utils/gladia_api_utils/run_process.py
Labels: type: fix

#805 fix(dream-studio): no longer returns 2 times the asked number of samples
  src/apis/text/image/image-generation-models/dream-studio/dream-studio.py
Labels: priority: high, status : confirmed, type: fix, ci: ready-to-merge

#806 feat(fastapify): v0 of fastapify
  src/api_utils/gladia_api_utils/apis_for_subprocess.py
  src/api_utils/gladia_api_utils/fastapi_runner.py
  src/config.json
Labels: type: enhancement, ci: ready-to-merge

#807 feat(fastapify): prepare os
  src/base.Dockerfile
  src/run_server.sh
  src/tools/venv-builder/envs/common/base.yaml
Labels: type: enhancement, ci: ready-to-merge, ci: build-base

#809 feat: image enhancement task
  src/api_utils/gladia_api_utils/model_architectures/Maxim.py
  src/api_utils/gladia_api_utils/model_architectures/__init__.py
  src/apis/image/image/enhancement-models/.task_metadata.yaml
  src/apis/image/image/enhancement-models/FiveK/FiveK.py
  src/apis/image/image/enhancement-models/FiveK/__init__.py
  src/apis/image/image/enhancement-models/FiveK/env.yaml
  src/apis/image/image/enhancement-models/LOL/LOL.py
  src/apis/image/image/enhancement-models/LOL/__init__.py
  src/apis/image/image/enhancement-models/LOL/env.yaml
  src/apis/image/image/enhancement-models/test_enhancement.py
  src/apis/image/image/enhancement.py
Labels: type: enhancement, type: new model, priority: medium, status : confirmed, ci: ready-to-merge, ci: force-build-gladia

#808 ci(test): switch to pytest
  .github/workflows/gladia-builder.yml
Labels: type: ci, ci: ready-to-merge

#810 ci(deploy): check aipi readiness
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#811 ci(deploy): another try to fix slack env webhook
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#812 ci(slack): use a run trigger for slack notifier
  .github/workflows/deploy-completion.yml
  .github/workflows/gladia-latest-deploy.yml
Labels: type: ci, ci: ready-to-merge

#815 test(enhancement): change test values
  src/apis/image/image/enhancement-models/.task_metadata.yaml
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: test

#817 perf(enhancement): keep in memory FiveK & LOL models
  src/apis/image/image/enhancement-models/FiveK/env.yaml
  src/apis/image/image/enhancement-models/LOL/env.yaml
  src/env.yaml
Labels: priority: high, status : confirmed, ci: ready-to-merge, type: performance, ci: force-build-gladia

#816 perf(CFMNet): reduce module to imports
  src/apis/image/image/deblurring-models/CMFNet/CMFNet.py
  src/apis/image/image/deblurring-models/CMFNet/model/CMFNet.py
  src/apis/image/image/deblurring-models/CMFNet/model/block.py
Labels: priority: high, status : confirmed, ci: ready-to-merge, type: performance

#818 test(deblurring): update test files
  src/apis/image/image/deblurring-models/.task_metadata.yaml
Labels: priority: medium, status : confirmed, ci: ready-to-merge, type: test

#819 feat(fastapify): v1 of the fastapification of submodules
  src/api_utils/gladia_api_utils/apis_for_subprocess.py
  src/api_utils/gladia_api_utils/casting.py
  src/api_utils/gladia_api_utils/fastapi_runner.py
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/image/image/colorization-models/deoldify-artistic/deoldify-artistic.py
  src/apis/image/image/colorization-models/deoldify-stable/deoldify-stable.py
  src/apis/image/image/super-resolution-models/latent-sr/latent-sr.py
  src/apis/image/image/super-resolution-models/latent-sr/ldm/modules/image_degradation/utils/test.png
  src/apis/image/text/ocr-models/tesseract-default/file.txt
  src/apis/text/image/image-generation-models/dream-studio/unsafe.png
  src/apis/text/image/image-generation-models/stable-diffusion/unsafe.png
  src/base.Dockerfile
  src/config.json
  src/gpu.Dockerfile
  src/main.py
  src/run_server.sh
  src/tools/venv-builder/envs/common/base.yaml
  src/unit-test/test.png
Labels: type: enhancement, ci: ready-to-merge, ci: build-base

#823 build(test): set log level to DEBUG
  .github/workflows/gladia-builder.yml
Labels: priority: critical, status : confirmed, ci: ready-to-merge

#825 feat(whisper): add openai whisper to transcription
  src/apis/audio/text/audio-transcription-models/coqui_english_huge_vocab/coqui_english_huge_vocab.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-base/.model_metadata.yaml
  src/apis/audio/text/audio-transcription-models/openai-whisper-base/__init__.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-base/openai-whisper-base.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-large/.model_metadata.yaml
  src/apis/audio/text/audio-transcription-models/openai-whisper-large/__init__.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-large/openai-whisper-large.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-medium/.model_metadata.yaml
  src/apis/audio/text/audio-transcription-models/openai-whisper-medium/__init__.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-medium/openai-whisper-medium.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-small/.model_metadata.yaml
  src/apis/audio/text/audio-transcription-models/openai-whisper-small/__init__.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-small/openai-whisper-small.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-tiny/.model_metadata.yaml
  src/apis/audio/text/audio-transcription-models/openai-whisper-tiny/__init__.py
  src/apis/audio/text/audio-transcription-models/openai-whisper-tiny/openai-whisper-tiny.py
  src/apis/audio/text/audio-transcription.py
  src/env.yaml
Labels: type: enhancement, ci: ready-to-merge

#824 feat(submodule): add support for enum, list, tuple, set as inputs + fix description
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/image/image/background-replacement-models/.task_metadata.yaml
  src/apis/image/image/background-replacement-models/__init__.py
  src/apis/image/image/background-replacement-models/mobilenet/.model_metadata.yaml
  src/apis/image/image/background-replacement-models/mobilenet/__init__.py
  src/apis/image/image/background-replacement-models/mobilenet/mobilenet.py
  src/apis/image/image/background-replacement.py
Labels: type: enhancement, help wanted, ci: ready-to-merge

#832 feat(ocr): add all type of file text extraction
  src/api_utils/gladia_api_utils/file_management.py
  src/apis/image/text/ocr-models/tesseract-default/file.txt
  src/apis/image/text/ocr-models/textract-extractor/.model_metadata.yaml
  src/apis/image/text/ocr-models/textract-extractor/__init__.py
  src/apis/image/text/ocr-models/textract-extractor/env.yaml
  src/apis/image/text/ocr-models/textract-extractor/textract-extractor.py
  src/base.Dockerfile
  src/config.json
Labels: type: enhancement, ci: ready-to-merge, ci: build-base
