Repository gladiaio/gladia, pull requests merged in 2023-01, with the labels that each got.

#1023 refactor(language-detection): rename papluca to jb2k_bert
  src/apis/text/text/language-detection/jb2k_bert-base-multilingual-cased-language-detection/__init__.py
  src/apis/text/text/language-detection/jb2k_bert-base-multilingual-cased-language-detection/env.yaml
  src/apis/text/text/language-detection/jb2k_bert-base-multilingual-cased-language-detection/jb2k_bert-base-multilingual-cased-language-detection.py
Labels: priority: low, type: refactor, ci: ready-to-merge

#1022 refactor(whisper): can be pinned
  src/apis/audio/text/audio-transcription/openai-whisper/env.yaml
  src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
  src/env.yaml
Labels: priority: medium, status : confirmed, type: refactor, ci: ready-to-merge, ci: force-build-gladia

#1018 feat(array-type): new type for sentiment-analysis and emotion-recognition
  src/api_utils/gladia_api_utils/submodules.py
  src/apis/text/text/emotion-recognition/mrm8488-t5-base-finetuned-emotion/mrm8488-t5-base-finetuned-emotion.py
  src/apis/text/text/emotion-recognition/task.yaml
  src/apis/text/text/sentiment-analysis/distilbert-base-uncased-finetuned-sst-2-english/distilbert-base-uncased-finetuned-sst-2-english.py
  src/apis/text/text/sentiment-analysis/distilbert-base-uncased/distilbert-base-uncased.py
  src/apis/text/text/sentiment-analysis/task.yaml
  src/apis/text/text/sentiment-analysis/zero-shot-classification-facebook-bart-large-mnli/zero-shot-classification-facebook-bart-large-mnli.py
Labels: type: enhancement, priority: high

#1026 refactor: delete deepspeed based models
  src/apis/text/text/language-detection/jb2k_bert-base-multilingual-cased-language-detection/__init__.py
  src/apis/text/text/language-detection/jb2k_bert-base-multilingual-cased-language-detection/env.yaml
  src/apis/text/text/language-detection/jb2k_bert-base-multilingual-cased-language-detection/jb2k_bert-base-multilingual-cased-language-detection.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/.model_metadata.yaml
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/__init__.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed.py
  src/apis/text/text/named-entity-recognition/dbmdz-bert-large-cased-finetuned-conll03-english_deepspeed/env.yaml
Labels: type: refactor, ci: ready-to-merge

#1027 fix(audio-transcription/whisper): replace DEFAULT_MODEL to DEFAULT_MODEL["model"]
  src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#1029 docs(readme): update supported hardware
  README.md
Labels: type: documentation, priority: low, status : confirmed, ci: ready-to-merge

#1030 refactor(audio-transcription/whisper): do not load default model until needed
  src/apis/audio/text/audio-transcription/openai-whisper/openai-whisper.py
Labels: priority: medium, status : confirmed, type: refactor, ci: ready-to-merge

#1107 fix: api_utils import shutil
  src/api_utils/gladia_api_utils/model_management.py
Labels: priority: critical, type: fix, ci: ready-to-merge

#1108 fix: use cache for server env
  src/run_server.sh
Labels: type: fix

#1109 fix: keep server env + moar debug
  src/run_server.sh
  src/tools/venv-builder/create_custom_envs.py
Labels: type: fix

#1031 feat(gladia): add tritonserver and switch keyword-extraction to use it
  src/api_utils/gladia_api_utils/triton_helper/TritonClient.py
  src/apis/text/text/keyword-extraction/keybert-paraphrase-multilingual-MiniLM-L12-v2/.git_path
  src/apis/text/text/keyword-extraction/keybert-paraphrase-multilingual-MiniLM-L12-v2/keybert-paraphrase-multilingual-MiniLM-L12-v2.py
  src/docker/lite.Dockerfile
  src/run_server.sh
Labels: type: enhancement, priority: medium, status : confirmed, ci: ready-to-merge, ci: build-base

#1110 fix: add missing image to video folder
  src/apis/image/video/.empty
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#1112 fix: add missing video-to-audio folder
  src/apis/video/audio/.empty
Labels: priority: critical, status : confirmed, type: fix, ci: ready-to-merge

#1113 docs(readme): add supported hardware!
  README.md
Labels: ci: ready-to-merge
